export const portalEN: LanguageKeyValueMap = {

	initializationError: 'Initialization Error',
	unableLoadRequiredData: 'Unable to load required data',
	connectionError: 'Connection Error',
	unableSaveChanges: 'Unable to save changes',
	saveSettingsFailed: 'Save settings failed',
	PortalUriRequiedForSmtpSettings: 'Please confirm that the "Portal URI" in "UI Settings" is already provided before you save the email settings.',
	WorkerJobMaxExecTimeIsInvalid: 'Maximal exec time should be between 0(s) and 2147481(s).',
	WorkerTaskMaxCountIsInvalid: 'Task per worker should be between 0 and 100.',
	// Common
	Save: 'Save',
	Ok: 'OK',
	Close: 'Close',
	Cancel: 'Cancel',
	Reset: 'Reset',
	Upload: 'Upload',
	Update: 'Update',
	Delete: 'Delete',
	SaveChanges: 'Save Changes',
	Dismiss: 'Dismiss',
	DismissAll: 'Dismiss All',
	ShowDetails: 'Show Details',
	ShowAll: 'Show All',
	Name: 'Name',
	Color: 'Color',
	Icon: 'Icon',
	GettingReady: 'Getting Ready',
	ShowPassword: 'Show password',
	HidePassword: 'Hide password',
	Yes: 'Yes',
	No: 'No',
	Logo: 'Wyn Logo',
	Avatar: 'Avatar',

	// Collection Headers
	title: 'Name',
	creator: 'Creator',
	created: 'Created',
	modifier: 'Updated By',
	modified: 'Updated',
	emptyPageTip: 'There is no {{name}} file in the current system',

	// Portal Configuration
	pcPortalSetting: 'Portal Settings',
	pcSupportPJBG: 'Support formats: PNG, JPG, BMP, GIF',
	pcSupportICO: 'Support formats: ICO',
	pcTitle: 'Title',
	pcPortalUri: 'Portal Uri',
	pcPortalUriPlaceHolder: 'Portal home page url',
	pcTheme: 'Theme',
	pcTagsModel: 'Tags Model',
	pcTagsDisplay: 'Display Empty System Categories',
	pcAllowCustomSchedule: 'Allow User To Create Custom Schedule',
	pcEnableWebPageDocument: 'Enable webpage documents',
	pcAllowEditPersonalInformation: 'Allow User To Edit Personal Information',
	pcAllowEditPersonalTheme: 'Allow User To Edit Personal Theme',
	pcAllowUrlHideActions: 'Allow \'hideActions\' In Url',
	pcHideWelcomeScreen: 'Hide Welcome Screen On Document Portal',
	pcShowGlobalOrganization: 'Show Global Organization',
	pcHideActions: 'Hide Actions',
	pcHideActionsTip: 'Only works when Allow \'hideActions\' In Url option is off',
	pcHideActionsPlaceHolder: 'Please Set Hide Actions(Separated by commas)',
	pcHideDocumentListColumns: 'Hide Document List Columns',
	pcHideDocumentListColumnsPlaceHolder: 'Please Set Hide columns(Separated by commas)',
	pcEditPersonalInfo: 'Manage',
	pcEditPersonalInfoTooltip: 'Manage Custom Property',
	pcLargeLogo: 'Large Logo',
	pcLargeLogoDescription: 'This logo will be displayed in the upper left corner of Admin Portal',
	pcLargeLogoRecommended: 'Recommended size: 115px * 40px',
	pcSmallLogo: 'Small Logo',
	'pcSmallLogoDescription!en': 'This logo will be displayed in the upper left corner of Document Portal and Resource Portal',
	'pcSmallLogoRecommended!en': 'Recommended size: 40px * 40px',
	'pcSmallLogoDescription!zh': 'This logo will be displayed in the upper left corner of Portal',
	'pcSmallLogoRecommended!zh': 'Recommended size: 40px * 40px',
	pcTabIcon: 'Tab Icon',
	pcTabIconDescription: 'This logo will be displayed on the tab of the browser',
	pcTabIconRecommended: 'Recommended size: 16px * 16px',
	pcIdentitySetting: 'Login Page Settings',
	pcIdentityAdvanceSetting: 'Login Page Advance Settings',
	pcIdentityAdvanceSettingCss: 'Css',
	pcIdentityAdvanceSettingCssDesc: 'If you set the css, we will use this css instead of the builtin css in login page.',
	pcIdentityAdvanceSettingHtml: 'Html',
	pcIdentityAdvanceSettingHtmlDesc: 'The html will render after our login page content.',
	pcIdentityAdvanceSettingPreview: 'Preview',
	pcLoginLogo: 'Login Logo',
	pcLoginLogoDescription: 'This logo will be displayed in the login page',
	pcLoginLogoRecommended: 'Recommended size: 200px * 50px',
	pcLoginImage: 'Login Image',
	pcLoginImageDescription: 'This image will be displayed in the left of login page',
	pcLoginImageRecommended: 'Recommended size: 960px * 830px',
	pcLoginTip: 'Login Tip',
	pcLoginTipDescription: 'This tip message will be displayed in the login page',
	pcLoginPreview: 'Login Preview',
	pcWCAGCompatibility: 'WCAG Compatibility',
	pcEnableNewCreationPanel: 'Enable New Creation Panel',
	pcAutoDismissNotifications: 'Auto Dismiss Notifications',
	pcDurationOfNotifications: 'Duration of Notifications(s)',

	// SMTP
	emailSettingsTitle: 'Email Settings',
	smtpDialogTitle: 'Email Settings Test',
	smtpSendTestMail: 'Send',
	smtpSendTestMailTitle: 'Send Test Email',
	smtpRecipientMailAddress: 'Recipient Email Address',
	smtpServerAddressError: 'Incorrect server address',
	smtpServerPortError: 'Incorrect server port',
	smtpUsernameOrPasswordError: 'Incorrect username or password',
	smtpSendTestMailFail: 'Send test email failed',
	smtpSendTestMailSuccess: 'Send test email successfully',
	smtpTestMailSubject: 'Test e-mail',
	smtpTestMailBody: 'This is a configuration test email',
	emailDomainValidationTitle: 'Email Domain Validation',
	enableDomainValidation: 'Enable Domain Validation',
	validEmailDomains: 'Valid Email Domains',
	enable: 'Enable',
	disable: 'Disable',
	mailProtocol: 'Mail Protocol',
	googleClientID: 'Client ID',
	googleClientSecret: 'Client Secret',
	senderName: 'Sender Name',
	senderEmail: 'Sender E-Mail',
	serverAddress: 'SMTP Server Address',
	serverPort: 'SMTP Server Port',
	enableSsl: 'Enable SSL',
	login: 'Login',
	password: 'Password',
	useParentSettings: 'Use Parent Organization Settings',

	// Tags
	tagsAddTag: 'Add Category',
	tagsEditTag: 'Edit Category',
	tagsCreateTag: 'Create Category',
	tagsUpdateTag: 'Update Category',
	tagsEmptyName: 'Category name cannot be empty.',
	tagsInvalidName: 'Category name cannot start with $.',
	tagsNameExist: 'Category name "{{name}}" already exists.',
	tagsDragTip: 'Drag item to move it.',
	tagsTags: 'Categories',
	tagsDeleteTagConfirm: 'Do you want to delete this category "{{name}}" permanently?',
	tagsAddTagFailed: 'Add Category Failed',
	tagsEditTagFailed: 'Edit Category Failed',
	tagsDeleteTag: 'Delete Category',

	// Section Item
	dashHeaderDashboard: 'Dashboard',
	'portal!title': 'UI Settings',
	'portal!description': 'Configure Document and Admin portals',
	'scheduler!title': 'Scheduler',
	'scheduler!description': 'Scheduler module for GCES Prototype',
	'sharedResources!title': 'Shared Resources',
	'sharedResources!description': 'Shared resources module for GCES',
	'smtp!title': 'Email Settings',
	'smtp!description': 'Settings for the server mailing service',
	'queue!title': 'Worker queue settings',
	'queue!description': 'Settings for the worker queue',

	'semanticModeling!title': 'Data Model Settings',
	'semanticModeling!description': 'Data Model Settings',

	'documents!title': 'Documents',
	'documents!description': 'Documents Management',
	'images!title': 'Images',
	'images!description': 'Shared images for designing reports',
	'datasources!title': 'Data Sources',
	'datasources!description': 'Shared data sources for designing reports',
	'datasets!title': 'Data Sets',
	'datasets!description': 'Shared data sets for designing reports',

	'smtp!serverAddress': 'SMTP Server Address',
	'smtp!serverPort': 'SMTP Server Port',
	'smtp!enableSsl': 'Enable SSL',
	'smtp!login': 'Login',
	'smtp!password': 'Password',
	'smtp!senderName': 'Sender name',
	'smtp!senderEmail': 'Sender e-mail',
	'smtp!emailDomainValidation': 'Email Domain Validation',
	'smtp!emailDomains': 'Email Domains',
	'smtp!mailProtocol': 'Mail Protocol',
	'smtp!mailProtocol!SMTP': 'SMTP',
	'smtp!mailProtocol!GoogleAPI': 'Google API',
	'smtp!googleClientID': 'Client ID',
	'smtp!googleClientSecret': 'Client Secret',
	'googleAPIAuthTitle': 'Authorization',
	'googleAPIAuth': 'Authorize',
	'GoogleApisAuthFailed': 'Authorization failed',
	'GoogleApisAuthSuccess': 'Authorization success',
	'googleApisError_1': '$t(pcPortalUri) is not provided in $t(portal!title)',
	'googleApisError_2': 'Authorization has begun',
	'googleApisError_3': 'Authorization failed: {{message}}',
	'googleApisError_4': 'Authorization timeout',
	'googleApisError_5': 'Missing key information in redirect URL',
	'googleApisError_6': '$t(pcPortalUri) in redirect URL does not match',
	'googleApisError_7': 'The Refresh Token cannot be empty',

	'scheduleSettings!ignoreEmptyContent': 'Don\'t deliver the empty document',
	'scheduleSettings!disableManualAndOneTimeTask': 'Disable Manual and One-time task',
	'scheduleSettings!disableFileShare': 'Disable \"File Share\" delivery',

	'queue!maxWorkerTasks': 'Max tasks per worker',
	'queue!defaultExecLimit': 'Default exec time limit (s)',
	'queue!maxExecLimit': 'Maximal exec time (s)',

	'semanticModeling!alwaysDiscourageDistinct': 'Prevent generating DISTINCT(for Report)',

	'portal!theme': 'Theme',
	'portal!theme!Default': 'Default',
	'portal!theme!Light': 'Light',
	'portal!theme!ActiveReports Server': 'Orange',
	'portal!theme!Blue': 'Blue',
	'portal!theme!Red': 'Red',
	'portal!theme!Forest': 'Forest',
	'portal!theme!Dark Forest': 'Dark Forest',
	'portal!theme!Green': 'Green',
	'portal!theme!Warm Light': 'Warm Light',
	'portal!theme!Minimal Blue': 'Minimal Blue',
	'portal!defaultTagsMode': 'Tags Model',
	'portal!defaultTagsMode!List': 'List',
	'portal!defaultTagsMode!TreeView': 'TreeView',
	'customTheme!head': 'Custom Theme',
	GetCustomThemeContentError: 'Get custom theme content failed',
	GetBuiltInThemeContentError: 'Load built-in theme failed',

	'account-management!title': 'Account',
	'account-management-user!title': 'Users',
	'account-management-user!description': 'User management',
	'account-management-role!title': 'Roles',
	'account-management-role!description': 'Role management',
	'account-management-property!title': 'Custom Property',
	'account-management-property!description': 'Define UserContext values to add dynamic behavior for datasets, datasources, and other documents',
	'account-management-locked-users!title': 'Locked Users',
	'account-management-locked-users!description': 'Locked user management',
	'account-management-concurrence!title': 'Concurrence',
	'account-management-concurrence!description': '',
	'account-management-security-settings!title': 'Security Settings',
	'account-management-security-settings!description': 'Manage security settings',
	'account-management-claim-mappings!title': 'User Context',
	'account-management-claim-mappings!description': 'Claim mappings management',
	'sysconfig-license!title': 'License',
	'sysconfig-license!description': 'License activation',
	'sysconfig-security-provider!title': 'Security Providers',
	'sysconfig-security-provider!description': 'Security provider management',
	'sysconfig-external-provider!title': 'External Providers',
	'sysconfig-external-provider!description': 'External provider management',
	'sysconfig-client!title': 'Client',
	'sysconfig-client!description': 'Client management',

	'security-settings!title': 'Security',
	'system-management!title': 'System Management',
	'search!title': 'Search',
	EmptySearchResult: 'empty result',

	'resources!title': 'Resources',

	'configuration!title': 'Configuration',

	'tagsEditor!title': 'Categories',
	'tagsEditor!description': 'Manage document categories',
	'auditLogConfiguration!title': 'Auditing Settings',
	'auditLogConfiguration!description': 'configure audit log information',
	'documentThemeEditor!title': 'Default Document Theme',
	'documentThemeEditor!description': 'Configure document default theme',

	'wyn-plugin!title': 'Monitoring',
	'wyn-plugin!description': "Monitor workers' health",
	'reporting-plugin!title': 'Reporting',
	'reporting-plugin!description': '',
	'wyn-plugin-monitor!title': 'Workers',
	'wyn-plugin-monitor!description': '',
	'wyn-plugin-tasks!title': 'Tasks',
	'wyn-plugin-tasks!description': '',
	'shortcut-scheduler-settings!title': 'Scheduler Settings Shortcut',
	'shortcut-scheduler-settings!description': '',
	'shortcut-reports!title': 'Reports Shortcut',
	'shortcut-reports!description': '',
	'shortcut-images!title': 'Shared Images Shortcut',
	'shortcut-images!description': '',
	'shortcut-scheduler-settings!props!text': 'Scheduler Settings',
	'shortcut-reports!props!text': 'Reports',
	'shortcut-images!props!text': 'Shared Images',
	'shortcut-mapData!props!text': 'Map Data',
	'versionsInfo!title': 'Version Info',
	'versionsInfo!description': 'Version Info',
	'wynEnterprise': 'Wyn Enterprise',

	'Documents!title': 'Documents',
	'Account Management!title': 'Account',
	'Configuration!title': 'Configuration',
	'dbd!title': 'Dashboards',
	'dbd!description': 'Dashboards',
	'dbd!name': 'Dashboard',
	'rdl!title': 'Reports',
	'rdl!name': 'Report',
	'rdl!description': 'Reports',
	'smdsc!title': 'Data Models',
	'smdsc!name': 'Data Models',
	'smdsc!description': 'Data Models',
	'rdlx-template!title': 'Report Templates',
	'rdlx-template!description': 'Report Templates',
	'rdlx-master!title': 'Master Report',
	'rdlx-master!description': 'Master Report',
	'dataset!title': 'Datasets',
	'dataset!name': 'Datasets',
	'dataset!description': 'Datasets',

	'dsc!title': 'Data Sources',
	'dsc!name': 'Data Sources',
	'dsc!description': 'Data Sources',
	'image/jpeg,image/bmp,image/gif,image/png,image/svg!title': 'Images',
	'image/jpeg,image/bmp,image/gif,image/png,image/svg!name': 'Image',
	'image/jpeg,image/bmp,image/gif,image/png,image/svg!description': 'Images',
	'font/ttf,font/otf,font/woff,font/woff2,font/svg,font/eot,font/webfont!title': 'Font',
	'font/ttf,font/otf,font/woff,font/woff2,font/svg,font/eot,font/webfont!name': 'Font',
	'font/ttf,font/otf,font/woff,font/woff2,font/svg,font/eot,font/webfont!description': 'Font',
	'theme!title': 'Themes',
	'theme!name': 'Themes',
	'theme!description': 'Themes',
	'geoJson!title': 'Map Data',
	'geoJson!description': 'Map Data',
	'floorPlan!title': 'Floor Plan',
	'floorPlan!name': 'Floor Plan',
	'floorPlan!description': 'Floor Plan',
	'wbp!title': 'Web Page',
	'wbp!name': 'Web Page',
	'wbp!description': 'Web Page',

	'visual!title': 'Visualization',
	'visual!description': 'Visualization',

	'reporting!title': 'Feature Settings',
	'reporting!name': 'Report',
	'reporting!description': 'Configure WynReports',
	'reporting!parametersPanelPosition': 'Parameter panel position',
	'reporting!parametersPanelPosition!Top': 'Top',
	'reporting!parametersPanelPosition!Right': 'Right',
	'reporting!showParametersPanelByDefault': 'Show parameters panel by default',
	'previewPagesSettings_limitPreviewPages': 'Limit preview pages',
	'previewPagesSettings_previewPages': 'Preview pages',
	'previewPagesSettingsTooltip': 'Limit preview pages setting limits number of report pages to be rendered in viewer. You can render a full report by clicking \'Run Full Report\'. This won\'t affect scheduling and exporting.',
	'reporting!disableFocusTimer': 'Focus always visible',
	'reporting!hideBlankRDLReport': 'Hide blank RDL report',
	'hideBlankRDLReportTooltip': 'Hide the built-in Blank RDL Report template while creating reports.',
	'reporting!hideBlankPageReport': 'Hide blank Page report',
	'hideBlankPageReportTooltip': 'Hide the built-in Blank Page Report template while creating reports.',

	'scheduleSettings!title': 'Schedule Settings',
	'scheduleSettings!description': 'Schedule Settings management',

	'report-settings!title': 'WynReports Settings',
	'report-settings!description': 'WynReports Settings',
	'schedule-settings!title': 'Scheduling',
	'schedule-settings!description': 'Scheduling',

	// Nav Toolbar
	globalOrgName: 'Global',
	switchOrganization: 'Switch Organization',
	editProfileSetting: 'Edit Profile Setting',

	// Version Info
	'productVersion': 'Wyn Enterprise',
	'serverVersion': 'Server',
	'portalVersion': 'Portal',
	'pluginTitle': 'Plugins',
	'Portal': 'Portal Plugin',
	'Scheduler': 'Scheduler Plugin',
	'Shared Resources': 'Shared Resources Plugin',
	'Server plugin': 'Server Plugin',
	'Account Management Plugin': 'Account Management Plugin',
	'Dataset Management Plugin': 'Dataset Management Plugin',
	'GCES Dashboards': 'WynDashboards Plugin',
	'GCES Reporting': 'WynReports Plugin',
	DeleteDocumentError: 'Error deleting document',

	storageIntervalSettingsUnitHours: 'Hours',
	storageIntervalSettingsUnitDays: 'Days',
	storageIntervalSettingsUnitWeeks: 'Weeks',
	storageIntervalSettingsUnitMonths: 'Months',
	storageIntervalSettingsUnitYears: 'Years',
	storageIntervalSettingsUnitForever: 'Forever',
	storageIntervalSettingsLabel: 'Max. storage interval',

	'UpdateNotificationTips': 'There is a new version "Version {{newestVersion}}" to update.',
	'UpdateNotificationTipsViewMore': 'Click here to view more info...',
	'UpdateNotificationSkip': 'Skip this version',
	'UpdateNotificationSkipTips': 'Skip until another version published',
	'UpdateNotificationSkipVersionError': 'Failed to skip the version',
	'UpdateNotificationSkipVersionSuccess': ' Skipped version successfully',
	'UpdateNotificationSkipVersionSuccessDetail': 'Success to skip the version "Version {{version}}"',
	'vsReleaseTime': 'Release Date:',
	'vsSummary': 'Summary:',
	'vsViewDetail': 'View Detail',

	// AdminUploadPanel
	dzDragDrop: 'Drag & Drop',
	dzFiles: 'Files',
	dzClickToSelect: 'or click here to select',
	dzUpload: 'Upload',
	Commit: 'Commit',
	UploadModeTitle: 'When document already exists, your upload mode:',
	UploadModeTitleVisual: 'When visualization already exists(without id), your upload mode:(for visualization which has same id with existing, the mode will be ignored)',
	Overwrite: 'Overwrite document',
	KeepBoth: 'Keep both documents',
	Collapse: 'Collapse',
	Expand: 'Expand',
	ReadyToCommit: 'Ready To Commit',
	UploadError: 'Upload Failed',
	uploadErr_200_001: 'Unsupported document type',
	uploadErr_200_002: 'SharedResource plugin not found',
	uploadErr_200_003: 'Uploading failed.',
	uploadErr_200_004: 'Unsupported "OverwritePolicy".',
	uploadErr_200_005: 'Something wrong.',
	uploadErr_200_006: 'Empty file',
	uploadErr_200_007: 'Validation error',
	uploadErr_200_008: 'Permission denied',
	uploadErr_200_009: 'Document reserved by system cannot be overwritten.',
	uploadErr_200_010: 'The version({{newVersion}}) is lower than or equal to current({{existingVersion}}).',
	UploadSuccess: 'Upload successfully',
	UploadErrors: 'Upload failed',

	err_20015: 'Category name "{{tagName}}" cannot start with \"$\".',
	err_20016: 'Category with the id "{{tagId}}" not found.',
	err_20017: 'Category with the name "{{name}}" already exists.',
	err_20018: 'Category with the url "{{urlName}}" already exists.',
	err_20019: 'Category with the order "{{order}}" already exists.',
	err_20029: 'Can not use system reserved tag name "{{ name }}".',
};
