export const portalResourceES: LanguageKeyValueMap = {
	'createFloorPlan!name': 'Create Floor Plan',
	'createFloorPlan!description': 'Create Floor Plan',
	'modifyFloorPlan!name': 'Edit...',
	'modifyFloorPlan!description': 'Edit this Floor Plan',
	'floorPlan!name': 'Floor Plan',
	'other!name': 'OTHER',
};

export const shareResourceES: LanguageKeyValueMap = {
};

export const designerResourceES: LanguageKeyValueMap = {
	// common
	FloorPlanDesigner: 'Floor Plan Designer',
	Save: 'Save',
	Untitled: 'Untitled',
	Apply: 'Apply',
	Cancel: 'Cancel',
	Yes: 'Yes',
	No: 'No',
	OK: 'OK',
	Close: 'Close',
	EditName: 'Edit Name',
	Name: 'Name',
	Description: 'Comment',
	actionBar_importImage: 'Import Image',
	actionBar_path: 'Path',
	actionBar_rect: 'Rectangle',
	actionBar_ellipsis: 'Ellipsis',
	actionBar_zoomIn: 'ZoomIn',
	actionBar_zoomOut: 'ZoomOut',
	actionBar_name: 'Name',
	menuItem_rename: 'Rename',
	menuItem_delete: 'Delete',
	menuItem_delete_shortCut: 'BACKSPACE',
	menuItem_group: 'Group',
	menuItem_group_shortCut: 'G',
	menuItem_unGroup: 'Ungroup',
	menuItem_unGroup_shortCut: 'G',
	menuItem_removeBgImage: 'Remove Image',
	areaNamePattern: 'Shape{{number}}',
	areaNameRegex: '^Shape(\\d+)$',
	'preview-floorPlan!title': 'Floor Plan Preview',

	Confirmation: 'Unsaved Change Detected',
	CloseFloorPlanDesignerConfirm: 'Unsaved changes detected. Would you like to proceed?',

	// error info
	EmptyName: 'Empty Name',
	AreaNameExist: '"{{name}}" already exists.',
	FloorPlanSaveError: 'Floor plan save failed',
	PleaseInputName: 'Please input floor plan name.',
	FloorPlanNameOnlySapcesError: 'The floor plan name is invalid. Please do not use spaces only as floor plan name.',
	FloorPlanGraphEmptyError: 'Floor plan graph can not empty.',
	updateFloorError: 'Update floor plan failed',
	loadFloorError: 'Load floor plan failed',
	createFloorError: 'Add floor plan failed',
	err_300000: 'Unexpected error occurs, error message: {{message}}',
	err_300001: 'Document with name "{{Title}}" already exists.',
	err_300002: 'Document is referred by other documents.',
	err_300003: 'Access denied.',
	err_300004: 'Invalid parameter detected.',
	err_300005: 'Document was removed.',
	err_300006: 'Document not found.',
	err_300007: 'Document name can not be empty.',
};
