export const wizardES: LanguageKeyValueMap = {
	UseConfigString: 'Use Configuration String(Advanced)',
	Name: 'Name',
	User: 'User',
	Server: 'Server',
	Host: 'Host',
	Port: 'Port',
	Password: 'Password',
	Database: 'Database',
	CommandTimeout: 'Command Timeout(s)',
	noSearchResultTip: 'no result',
	loadingDatabases: 'Loading Databases...',
	Service_Name: 'Service Name',
	searchPlaceHolder: 'Please input to search',
	dataSource: 'Data Source',
	CommandTimeoutLimitation: 'Command timeout must be an integer value',
	testConnection: 'Test Connection',

	'createAnalysisModel!name': 'Create Data Model',
	selectModelType: 'Select model type',
	specifyDatasource: 'Specify a data source',
	configDatasource: 'Config data source',
	selectTableAndView: 'Select tables and views',
	generateModel: 'Generate a model',
	filterItems: 'Filter items by name:',
	findAdditionRelations: 'Include current relations',
	findRelatedTables: 'Include related tables',
	selectOrClearAllItems: 'Select or clear all items:',
	modelAlreadyExist: "Data model '{{name}}' already exist.",
	invalidAnalysisModelName: 'The data model name is invalid. Please do not use restricted symbols < > \ : ? * / | " and do not use . (dot) as the first symbol in the data model name.',

	back: 'Back',
	next: 'Next',
	done: 'Done',
	close: 'Close',

	'DataSourceDisplayName!Oracle': 'Oracle',
	'DataSourceDisplayName!SqlServer': 'SQL Server',
	'DataSourceDisplayName!MySql': 'Mysql',
	'DataSourceDisplayName!Postgres': 'Postgres',
	'DataSourceDisplayName!Hive': 'Hive',
	'DataSourceDisplayName!Hana': 'Hana',
	'DataSourceDisplayName!TimeScale': 'TimeScale',
	'DataSourceDisplayName!MonetDB': 'MonetDB',
	'DataSourceDisplayName!ALIAnalyticDBMySql': 'AnalyticDB(MySQL)',
	'DataSourceDisplayName!MariaDB': 'MariaDB',
	'DataSourceDisplayName!Db2': 'Db2',
	'DataSourceDisplayName!BigQuery': 'BigQuery',
	'DataSourceDisplayName!Json': 'Json',

	tables: 'Tables',
	views: 'Views',

	noDataSource: 'Could not find available data source',

	dataSourceType: 'Data Source Type',
	'dataSourceType!0': 'Embedded Data Source',
	'dataSourceType!1': 'Shared Data Source',
	dataProvider: 'Data Provider',
	loadingDatasources: 'Loading Data Sources...',
	ProjectId: 'Project Id',
	OAuthServiceAcctEmail: 'Service Account',
	OAuthPvtKeyPath: 'Key Path',
	OAuthAccessToken: 'Access Token',
	OAuthRefreshToken: 'Refresh Token',
	'BigQuery-OAuthClientId': 'Client Id',
	'BigQuery-OAuthClientSecret': 'Client Secret',
	AuthMode: 'AuthMode',

	// Cache Mode
	data: 'Data',
	getData: 'Get Data',
	chooseDataSource: 'Choose data source',
	selectAndEditTables: 'Select and edit tables',
	selectAndEditColumns: 'Select and edit columns',
	loadData: 'Load data',
	addTableBySql: 'Add Table By Sql',
	editTableBySql: 'Edit Table By Sql',
	tableName: 'Table Name',
	type: 'Type',
	alias: 'Alias',
	addTable: 'Add Table',
	editTable: 'Edit Table',
	editColumn: 'Edit Column',
	saveAndContinueAdding: 'Save And Continue Adding',
	addColumnBySql: 'Add Column By Sql Expression',
	editColumnBySql: 'Edit Column By Sql Expression',
	columnName: 'Column Name',
	totalNumberOfRows: 'Total Number Of Rows',
	progress: 'Progress ',
	status: 'Status',
	calculating: 'Calculating',
	downloadLog: 'Download Log',
	ok: 'OK',
	ReadData: 'Read data',
	FindDatabase: 'Find cache storage',
	TransportData: 'Transport data',
	LoadToDatabase: 'Load to cache storage',
	loading: 'Loading',
	succeeded: 'Successful',
	failed: 'Failed',
	reloadFailedTables: 'Reload Failed Tables',
	getLockError: 'The lock expires, and the designer will automatically save and close',
	autoSave: 'Auto Save',
	modelAdaptation: 'Model Adaptation',
	cannotDeleteLastEntity : 'Cannot delete the last entity',
	cannotDeleteLastAttribute : 'Cannot delete the last Attribute',
	reload: 'Reload',
	lastLoadTime: 'Last Load Time',
	retry: 'Retry',
	exit: 'Exit',
	reloadData: 'Reload Data',
	selectTablesToReload: 'Select tables to reload',
	'unsupportedDatatype!title': 'Unsupported data types',
	'unsupportedDatatype!content': 'The unsupported columns are: {{column}}',
	tableWithParameterHint: 'It is not allowed to select tables with parameters.',
	table: 'Table',
	view: 'View',
	sql: 'SQL',

	// data type
	Number: 'Number',
	Text: 'Text',
	Boolean: 'Boolean',
	Binary: 'Binary',
	GUID: 'GUID',
	Date: 'Date',
	DateTime: 'DateTime',
};