export const personalTagManagementEN: LanguageKeyValueMap = {
	Name: 'Name',
	Color: 'Color',
	Icon: 'Icon',

	Delete: 'Delete',
	Cancel: 'Cancel',
	Close: 'Close',

	naCategory: 'Personal Category',
	naCategorySettingsTitle: 'Manage personal Categories',
	naTagEditorTitle: 'Drag item to move it',
	naTagEditorAdd: 'Add Category',
	naTagEditorCreate: 'Create Category',
	naTagEditorUpdate: 'Update Category',
	naTagEditorTreeRootTitle: 'Personal Categories',
	naTagEditorEmptyTip: 'No personal category is selected',
	naTagEditorDeleteTitle: 'Delete Category',
	naTagEditorDeleteConfirm: 'Do you want to delete this category "{{name}}" permanently?',
	naTagEditorOK: 'OK',
	naTagEditorClose: 'Close',
	naTagEditorCancel: 'Cancel',
	naTagEditorAddFailed: 'Add Category Failed',
	naTagEditorUpdateFailed: 'Update Category Failed',
	naTagEditorCategoryName: 'Category name',
	naTagEditorEmptyName: 'Category name cannot be empty.',
	naTagEditorInvalidName: 'Category name cannot start with $.',
	naTagEditorUpdateListError: 'Error updating categories list',
	naTagEditorDeleteError: 'Error deleting category',
	naTagEditorMoveError: 'Move Category Failed',

	err_20015: 'Category name "{{tagName}}" cannot start with \"$\".',
	err_20016: 'Category with the id "{{tagId}}" not found.',
	err_20017: 'Category with the name "{{name}}" already exists.',
	err_20018: 'Category with the url "{{urlName}}" already exists.',
	err_20019: 'Category with the order "{{order}}" already exists.',
	err_20029: 'Can not use system reserved tag name "{{ name }}".',
};
