export const portalResourceES: LanguageKeyValueMap = {
  'shortcut-categories!description': '',
  'shortcut-categories!props!text': 'Categories',
  'shortcut-categories!title': 'Categories Shortcut',
  'geojson-storge-management!title': 'GeoJson',
  'geojson-storge-management!description': 'GeoJson Storge Management',
  'shortcut-themes!description': '',
  'shortcut-themes!props!text': 'Themes',
  'shortcut-themes!title': 'Themes Shortcut',
  'shortcut-image!description': ' ',
  'shortcut-image!props!text': 'Images',
  'shortcut-image!title': 'Images Shortcut',
  'rename-geo!name': 'Rename document',
  'rename-geo!description': 'Rename document'
};

export const shareResourceES: LanguageKeyValueMap = {
  // Header
  headerItemTextUploadNew: 'Upload Document',
  headerItemHeaderAddNew: 'Add new...',
  headerItemTextAdminPortal: 'Admin Portal',
  headerItemTextLogout: 'Logout',
  repeatName: 'Document({{newName}}) already exists.',
  renameDocNotFound: 'Document not found(Maybe has been removed. Please refresh the page).',
  noRenameDocPermission: 'No permission to rename the document.',
   // Upload Dialog
  udTextFiles: '{{count}} file',
  udTextFiles_plural: '{{count}} files',
  udTitleUpload: 'Upload',
  udTitleUploading: 'Uploading...',
  udTextStatusNoFiles: 'no files selected',
  udTextStatusInitializing: 'initializing...',
  udTextStatusInProgress: '{{count}} of {{total}} uploaded',
  udTextStatusReadyToCommitPartial: 'Ready to commit {{countText}} out of {{total}}',
  udTextStatusReadyToCommit: 'Ready to commit!',
  udHeaderInvalid: 'Invalid',
  udHeaderUnresolved: 'Unresolved',
  udHeaderAlreadyExists: 'Already exist',
  udHeaderReadyToCommit: 'Ready to commit',
  udHeaderUploading: 'Uploading',
  udBtnTextCommit: 'Commit',
  udBtnTextCommitValidOnly: 'Commit Valid Only',
  udBtnTextCancel: 'Cancel',
  udDNDTextDropFiles: 'Drag & Drop Files Here',
  udDNDTextClickHere: 'or click here to select files',
   // Upload File Item
  ufiTextUploading: 'Uploading...',
  ufiBtnTitleKeepBoth: 'Keep both documents',
  ufiBtnTitleOverwrite: 'Overwrite document',
   // Upload Saga
  usErrorTextSessionError: 'Upload session error',
  usErrorTextValidationError: 'Validation Error',
  usErrorTextValidationErrorDetails: 'We were unable to get validation status. Sorry',
  usErrorTextUploadCommitError: 'Upload Error',
  usErrorTextUploadCommitErrorDetails: 'We were unable to commit. Sorry',
  usErrorTextCancelationError: 'We couldn\'t cancel uploading of this file. Sorry',
   // Upload Other
  uoTextUnknownFileType: 'Unknown File Type',
  uoTextUnsupportedFileType: 'Unsupported File Type',
  rename: 'Rename Document',
  untitled: 'Untitled',
  save: 'Save',
  cancel: 'Cancel',
  name: 'Name',
  description: 'Description',
  OK: 'OK',
  Close: 'Close',
  messageBox: 'Message Box',
  hierarchyEditorTitle: 'Hierarchy Editor',
  geoJsonSearchPlaceHolder : 'search geojson',
  noGeoJsonTip: 'No GeoJson, Please Upload Geojson first',
  noGeoJsonMatchTip: 'No matched GeoJson Matched',
  dropGeojsonHere: 'Drop GeoJson Here',
  joinTitle: 'Join',
  equals: 'Equals',
  joinTo: 'Join To',
  joinInfo: 'Select propety and value from "{{leftTableTitle}}" which used to refer to "{{rightTableTitle}}"',
  error_300000: 'Unknow Error!',
  error_300001: 'Document has existed!',
  error_300002: 'Document is referred by another document!',
  error_300003: 'Access Denied!',
  error_300004: 'Invalid Document!',
  error_300005: 'Document was removed!',
  error_300006: 'Document was not found!',
  UnknowError: 'Unknown Error!',
};
