export const userES: LanguageKeyValueMap = {
	// common
	cmNoMembersInOrg: 'No members in Organization',

	UserManagement: 'User Management',
	Yes: 'Yes',
	Edit: 'Edit',
	Delete: 'Delete',
	Save: 'Save',
	Cancel: 'Cancel',
	Close: 'Close',
	AddUser: 'Create User',
	SelectMenbers: 'Select Members',
	EditUser: 'Edit User',
	SearchText: 'search text',
	DeleteUser: 'Delete User',
	RemoveUserFromOrg: 'Remove User from Organization',
	Username: 'Username',
	Email: 'Email',
	Mobile: 'Mobile Number',
	FirstName: 'First Name',
	LastName: 'Last Name',
	FullName: 'Full Name',
	Password: 'Password',
	ConfirmPassword: 'Confirm Password',
	Roles: 'Roles',
	Provider: 'Provider',
	Organizations: 'Organizations',
	Status: 'Status',
	Enabled: 'Enabled',
	Disabled: 'Disabled',
	Enable: 'Enable',
	Disable: 'Disable',
	Locked: 'Locked',
	Actions: 'Actions',
	GetUsersError: 'Get users error',
	UsernameIsRequired: 'Username is required',
	UsernameAlreadyExists: 'Username already exists',
	EmailIsRequired: 'Email is required',
	EmailIsInvalid: 'Email is invalid',
	EmailAlreadyExists: 'Email already exists',
	MobileAlreadyExists: 'Mobile already exists',
	WeakPasswordRequirement: 'Password can not be null',
	StrongPasswordRequirement: 'Password must be at least 8 characters in length, contain at least 1 lowercase letter, 1 uppercase letter and 1 number.',
	PasswordNotMatch: 'Password and confirm password do not match.',
	PasswordIsBlank: 'Password cannot only contain whitespace charaters',
	DeleteUserConfirmMessage: 'Do you want to delete user "{{user}}" permanently?',
	RemoveUserConfirmMessage: 'Do you want to remove user "{{user}}" from organization "{{organization}}"?',
	OneRolePerLine: ' (One role per line)',
	OneValuePerLine: ' (One value per line)',
	Import: 'Import',
	Export: 'Export',
	Users: 'Users',
	Template: 'Template',
	NewUserName: 'new user name',
	NewUserEmail: 'new user email',
	SelectValue: 'select value',
	NullValue: '<empty>',
	ImportUsers: 'Import Users',
	DragDropFile: 'Drag & Drop File Here',
	Or: 'or',
	ClickHere: 'click here',
	SelectFile: 'to select file',
	ExportTemplate: 'Export Template',
	UnlockUser: 'Unlock User',
	UnlockUserConfirm: 'Do you want to unlock user "{{user}}" ?',
	UserTemplate: 'user_template',
	ErrorRemoveAdminFromAdministratorRole: "Can not remove user '{{userName}}' from role '{{roleName}}'.",
	ImportUsersSuccessMsg: 'Successfully imported {{count}} user(s).',
	ImportUsersFailMsg: '{{count}} user(s) failed to import, <a href="{{url}}" target="_blank">click here for details</a>.',
	ImportUsersFailed: 'Import users failed.',

	// select members
	smSelectMembers: 'Select Members',
	smEmptyResult: 'empty result',
	smMembers: '({{count}} members)',
	smAddUser: 'Add',

	UserDetail: 'User Details',
	ShowSubOrg: 'Show the members of Sub-organization',
	NotShowSubOrg: 'Not show the members of Sub-organization',
	RemoveUser: 'Remove user from the current organization',

	udBasicInfo: 'Basic Information',
	udEmpty: '[empty]',
	NoOrganizations: '[No Organization]',
	NoRoles: '[No Role]',
	onlyNoMemberOfSubOrg: 'remove user from organization can only be used when not show the members of sub-organization',
	ecNoMemberTip: 'No Users in the organization. Please click',

	Error: 'Error',
	umError_1028: 'User "admin" can not be deleted.',
	umError_5010: 'You cannot remove yourself from the current organization.',
};