export const commonES: LanguageKeyValueMap = {
	cmAdd: 'Add',
	cmSave: 'Save',
	cmCancel: 'Cancel',
	cmEmptyResult: 'empty result',
	ecSelectMembers: 'Select Members',
	ecMembers: '({{count}} members)',

	rn_orgadmin: 'Organization Administrator',
	rn_administrator: 'Administrator',
	rn_Everyone: 'Everyone',
	globalOrgName: 'Global',

	'create-dataset': 'Create Dataset',
	'create-dataset-description': 'Create, view, edit and delete datasets.',
	'create-data-source': 'Create Data Source',
	'create-data-source-description': 'Create, view, edit and delete data sources.',
	'create-semantic-model': 'Create Semantic Model',
	'create-semantic-model-description': 'Create, view, edit and delete semantic models.',
	'create-dashboard': 'Create Dashboard',
	'create-dashboard-description': 'Create, view, edit and delete dashboards.',
	'view-dashboard': 'View Dashboard',
	'view-dashboard-description': 'View Dashboards.',
	'create-report': 'Create Report',
	'create-report-description': 'Create, view, edit and delete reports.',
	'view-report': 'View Report',
	'view-report-description': 'View Reports.',
	'schedule-reports': 'Schedule Report/Dashboard',
	'schedule-reports-description': 'Schedule Report/Dashboard.',
	'create-input-form': 'Create Input Form',
	'create-input-form-description': 'Create, view, edit and delete input forms.',
	'view-input-form': 'View Input Form',
	'view-input-form-description': 'View input forms.',
	'view-resource-portal': 'View Resource Portal',
	'view-resource-portal-description': 'View Resource Portal',
	'view-revision': 'View Revision',
	'view-revision-description': 'View revision logs.',
	'allow-sharing': 'Allow Sharing',
	'allow-sharing-description': 'Allow user to share documents to others.',
};