export const modelEN: LanguageKeyValueMap = {
	analysisModel: 'Data Model Designer',
	CloseAnalysisDesignerConfirm: 'Do you want to leave data model designer and discard the changes?',
	confirmation: 'Confirmation',
	yes: 'Yes',
	no: 'No',
	save: 'Save',
	cancel: 'Cancel',
	add: 'Add',
	setSecurityFilterValue: 'Set Filter Value(s)',
	undo: 'Undo',
	redo: 'Redo',
	validate: 'Validate',
	entities: 'Entities',
	addEntity: 'Add Entity',
	addLocalEntity: 'Add Local Entity',
	editLocalEntity: 'Edit Local Entity',
	addRelation: 'Add Relationship',
	resetLayout: 'Reset Layout',
	markPathStart: 'Mark Path Start',
	markPathEnd: 'Mark Path End',
	clearMark: 'Clear Mark',
	viewSettings: 'View Settings',
	updateAnalysisModel: 'Update Data Model',
	saveAnalysisModel: 'Save Data Model',
	Description: 'Description',
	comment: 'Comment',
	deleteRelation: 'Delete Relationship',
	delete: 'Delete',
	unpin: 'Unpin',
	pin: 'Pin',
	relationFromTo: 'from \'{{sourceEntity}}\'[{{sourceColumns}}] to \'{{targetEntity}}\'[{{targetColumns}}]',
	addAttribute: 'Add Attribute',
	deleteAttribute: 'Delete Attribute',
	deleteEntity: 'Delete Entity',
	search: 'Search',
	searchNoResult: 'no items',
	editorEmpty: '<Empty>',
	FetchDataFailed: 'Fetch data failed',
	ConnectSuccess: 'Connect successfully.',
	validateSuccess: 'Model validated successfully.',
	Properties: 'Properties',
	beHidden: 'Already hidden',
	saveTips: 'Please click "Save" to complete the creation of the model',
	untitled: 'Untitled',
	getDataTips: 'Please click "Get Data" to add tables first',
	Forbidden: 'Access denied',

	// cardinality
	'cardinality!0': '1 To 1',
	'cardinality!1': '1 To N',
	'cardinality!2': '0..1 To N',
	'cardinality!3': 'N To 1',
	'cardinality!4': 'N To 0..1',
	'cardinality!hint!0': 'One {{source}} record corresponds to one {{target}} record.',
	'cardinality!hint!1': 'One {{source}} record corresponds to many {{target}} records.',
	'cardinality!hint!2': 'Zero or one {{source}} record corresponds to many {{target}} records.',
	'cardinality!hint!3': 'Many {{source}} records correspond to one {{target}} record.',
	'cardinality!hint!4': 'Many {{source}} records correspond to zero or one {{target}} record.',

	// home
	diagram: 'Diagram',
	relationshipManagement: 'Relationship Management',
	settings: 'Settings',

	// relationship management
	available: 'Active',
	name: 'Name',
	fromEntity: 'From: Entities (Attributes)',
	toEntity: 'To: Entities (Attributes)',
	cardinality: 'Cardinality',
	bidirectionCrossFiltering: 'Bidirectional Cross Filter',

	// Data Type
	'DataType!0': 'Number',
	'DataType!1': 'Text',
	'DataType!2': 'Boolean',
	'DataType!3': 'Binary',
	'DataType!4': 'GUID',
	'DataType!5': 'Date',
	'DataType!6': 'DateTime',

	// Data Viz AI hint types
	Currency: 'Currency',
	ImageURL: 'Image URL',
	ImageBinary: 'Image Binary',
	GeoRegion: 'Geography (Region)',
	GeoLatitude: 'Geography (Latitude)',
	GeoLongitude: 'Geography (Longitude)',

	// Editor
	show: 'Show',
	empty: 'Empty',
	apply: 'Apply',
	textItem: '[{{count}} item]',
	textItem_plural: '[{{count}} items]',
	greaterThanMaxLength: 'Must be less than or equal to the maximum length {{ maxLength }}',
	notMatchPattern: 'Must match the regex {{ pattern }}',
	'multipleValues!label': '<...>',
	'multipleValues!title': 'multiple values',
	sourceEntity: 'Source Entity',
	targetEntity: 'Target Entity',
	sourceColumns: 'Source Attributes',
	targetColumns: 'Target Attributes',

	// Security Filter Editor
	filterExpression: 'Filter Expression',
	'securityFilterOperator!0': 'Equals',
	'securityFilterOperator!1': 'In',
	'securityFilterOperator!2': 'Not Equals',
	'securityFilterOperator!3': 'Not In',
	userContext: 'User Context',
	organizationContext: 'Organization Context',

	// user & organization context
	user_context_userid: 'user id',
	user_context_name: 'user name',
	user_context_email: 'email',
	user_context_phone_number: 'mobile phone',
	user_context_given_name: 'given name',
	user_context_family_name: 'family name',
	user_context_full_name: 'full name',
	user_context_role: 'role',
	user_context_tenant$Name: 'organization-Name',
	user_context_tenant$FromEmail: 'organization-FromEmail',
	organization_context_Name: 'Name',
	organization_context_FromEmail: 'FromEmail',

	// Model Setting
	dataSourceSetting: 'Data Source Settings',
	connectionString: 'Connection String',

	// notifications
	'pathNotFound!title': 'Path not found',
	'pathNotFound!Description': 'There is no connective path between entity {{label1}} and entity {{label2}}.',
	relationCheckFailed: 'Relations checking failed',
	multipleDirectRelations: 'There are multiple connective paths between entity {{name1}} and entity {{name2}}.',
	multiplePathRelations: 'There are multiple paths between entity {{name1}} and entity {{name2}}. Path1 is {{path1}}. Path2 is {{path2}}.',

	// Sidebar
	propertyTips: 'Select one or more model objects to set their properties.',
	'attribute!title': 'ATTRIBUTE',
	'entity!title': 'ENTITY',
	'relation!title': 'RELATION',
	'viewSettings!title': 'VIEW SETTINGS',
	CAT_NAMING: 'NAMING',
	CAT_INFORMATION: 'INFORMATION',
	CAT_COMMON: 'COMMON',
	CAT_RELATION: 'RELATION',
	CAT_APPEARANCE: 'APPEARANCE',
	PROP_Name: 'Name',
	PROP_ID: 'ID',
	PROP_IsNullable: 'Is Nullable',
	PROP_IsUnique: 'Is Unique',
	PROP_IsContainTimeZone: 'Contains Time Zone',
	PROP_Binding: 'Binding',
	PROP_IsHidden: 'Is Hidden',
	PROP_SecurityFilter: 'Security Filter',
	PROP_Cardinality: 'Cardinality',
	PROP_CrossFilter: 'Bidirectional Cross Filter',
	PROP_Inactive: 'Make Relation Inactive',
	PROP_Condition: 'Condition',
	PROP_ShowNodeLabel: 'Always Show Node Label',
	PROP_ShowLinkCardinality: 'Show Link Cardinality',
	attr_BindingType_binding: 'Binding',
	attr_BindingType_query: 'Query',
	field: 'Field',
	table: 'Table',
	view: 'View',
	sqlExpression: 'SQL Expression',
	sqlQuery: 'SQL Query',
	logicalDataType: 'Logical Data Type',
	dataVizAIHint: 'Data Category',
	CLRDataType: 'System Data Type',
	conditionSelectSourceEntity: 'please select source entity',
	conditionSelectTargetEntity: 'please select target entity',

	// confirm
	confirmDeleteAttribute: "Confirm to remove the attribute '{{attribute}}' on entity '{{entity}}'?",
	confirmDeleteRelation: "Confirm to remove the relation between '{{source}}' and '{{target}}'?",
	confirmDeleteEntity: "Confirm to remove the entity '{{name}}'?",
	withSecurityFilters: "Security filters that refer to '{{name}}' will be deleted as well.",
	withRelations: "Relations that refer to '{{name}}' will be deleted as well.",
	withSecurityFiltersAndRelations: "Security filters and Relations that refer to '{{name}}' will be deleted as well.",

	// property grid
	emptyListPlaceholder: 'Select an item to see properties',
	gridSearchPlaceholder: 'enter property name here...',
	closeSearchBtnTitle: 'Close',
	noCommonProperties: 'There are no common properties',
	textUnknownProperty: 'Unknown Property:',

	// preview
	preview: 'Preview ({{name}})',
	'preview!title': 'Preview',
	previewNoRows: 'Preview No Rows',
	previewNoResult: 'Preview No Results',
	'preview!attribute': 'Attribute',
	'preview!operator': 'Operator',
	'preview!value': 'Value',
	'preview!parameterName': 'Parameter Name',
	'preview!valueType': 'Value Type',
	'preview!securityFilter': 'Security Filter',
	'preview!entityParameter': 'Entity Parameter',

	// local table
	editEntityData: 'Edit Entity Data',
	headerName: 'Header Name',
	addRow: 'Add Row',
	addColumn: 'Add Column',
	textType: 'Text',
	numberType: 'Number',
	datetimeType: 'DateTime',
	renameColumnName: 'Rename',
	deleteColumn: 'Delete Column',
	importExcelFile: 'Import Excel File',
	selectFile: 'Select File...',
	AutoColumnName: 'Use First Row as Header',
	AllowHiddenSheets: 'Load Hidden Sheets',
	AllowDBNull: 'Convert empty cell to DBNull',
	FilePassword: 'FilePassword',
	FileUploaded: '{{file}} has been uploaded',
	FileUploadWithEmptyName: 'File has been uploaded',
	importCSVFile: 'Import CSV File',
	ColumnDelimiter: 'Column Delimiter',
	workSheet: 'WorkSheet',
	selectSheet: 'Select Sheet',
	calculateValuePrompt: 'Is-nullable and is-unique value is calculated by data of local entity.',
	shiftLeft: 'Shift Left',
	shiftRight: 'Shift Right',
	nullShowMessage: 'If you input string "NULL", it will be converted to null value automatically',

	fileSizeOverflow: 'File size overflow.',
	rowOverflow: 'Rows overflow. Maximum number of rows is {{maxRowCount}}.',
	columnOverflow: 'Columns overflow. Maximum number of columns is {{maxColumnCount}}.',
	rowColumnOverflow: 'Rows and Columns overflow. Maximum number of rows is {{maxRowCount}} and maximum number of columns is {{maxColumnCount}}.',
	overflowAlert: 'The sheet can not be selected, because its data is out of range. Maximum number of rows is {{maxRowCount}} and maximum number of columns is {{maxColumnCount}}.',

	// Notifications
	ntfDismiss: 'Dismiss',
	ntfDismissAll: 'Dismiss All',
	ntfShowDetails: 'Show Details',
	ntfShowAll: 'Show All',
	ntfError: 'ERROR',
	ntfWarning: 'WARNING',
	ntfInfo: 'INFO',
	notifications: 'Notifications',

	Unspecified: 'Unspecified',
	Contains: 'Contains',
	NotContains: 'NotContains',

	dataSourceValidateFailed: 'Data source verification failed.',
	'dataSourceValidateFailed!missing': 'The target does not exist.',
	'dataSourceValidateFailed!change': 'The target type has been changed.',
	validateDataSources: 'Validate data sources',
	getFileDataFailed: 'Failed to get file data.',
	emptyFile: 'File is empty.',
};