export const wizardEN: LanguageKeyValueMap = {
	UseConfigString: 'Use Configuration String(Advanced)',
	Name: 'Name',
	User: 'User',
	Server: 'Server',
	Host: 'Host',
	Port: 'Port',
	Password: 'Password',
	Database: 'Database',
	CommandTimeout: 'Command Timeout(s)',
	noSearchResultTip: 'no result',
	loadingDatabases: 'Loading Databases...',
	Service_Name: 'Service Name',
	searchPlaceHolder: 'Please input to search',
	dataSource: 'Data Source',
	CommandTimeoutLimitation: 'Command timeout must be an integer value',
	testConnection: 'Test Connection',

	'createAnalysisModel!name': 'Create Data Model',
	selectModelType: 'Select model type',
	specifyDatasource: 'Specify a data source',
	configDatasource: 'Config data source',
	selectTableAndView: 'Select tables and views',
	generateModel: 'Generate a model',
	filterItems: 'Filter items by name:',
	findAdditionRelations: 'Include current relations',
	findRelatedTables: 'Include related tables',
	selectOrClearAllItems: 'Select or clear all items:',
	modelAlreadyExist: "Data model '{{name}}' already exist.",
	invalidAnalysisModelName: 'The data model name is invalid. Please do not use restricted symbols < > \ : ? * / | " and do not use . (dot) as the first symbol in the data model name.',

	back: 'Back',
	next: 'Next',
	done: 'Done',
	close: 'Close',

	'DataSourceDisplayName!Oracle': 'Oracle',
	'DataSourceDisplayName!SqlServer': 'SQL Server',
	'DataSourceDisplayName!MySql': 'Mysql',
	'DataSourceDisplayName!Postgres': 'Postgres',
	'DataSourceDisplayName!Hive': 'Hive',
	'DataSourceDisplayName!Hana': 'Hana',

	tables: 'Tables',
	views: 'Views',

	noDataSource: 'Could not find available data source',
};