export const commonEN: LanguageKeyValueMap = {
	cmAdd: 'Add',
	cmSave: 'Save',
	cmCancel: 'Cancel',
	cmEmptyResult: 'empty result',
	ecSelectMembers: 'Select Members',
	ecMembers: '({{count}} members)',

	rn_orgadmin: 'Organization Administrator',
	rn_administrator: 'Administrator',
	rn_Everyone: 'Everyone',
	globalOrgName: 'Global',

	'data!title': 'DATA',
	'dashboards!title': 'DASHBOARD',
	'reports!title': 'REPORT',
	'portal!title': 'PORTAL',
	'others!title': 'OTHERS',
	'management!title': 'MANAGEMENT',

	'ViewResourcePortalTip': 'To create DataSources, DataSets, and Data Models, you must have access to view Resource Portal.',
	'ViewDashBoardTip': 'To create Dashboard, you must have access to view Dashboard.',
	'ViewReportTip': 'To create Report,  you must have access to view Report.',
	'ManageUserTip': 'Allow organization admin users to create/edit/delete users.',
	'AssignManageUserTip': 'Allow organization admin users to assign/unassign the manage user permission, And you must have permission to manage user before you can assign/unassign it.',

	'create-dataset': 'Create Dataset',
	'create-dataset-description': 'Create, view, edit and delete datasets.',
	'create-data-source': 'Create Data Source',
	'create-data-source-description': 'Create, view, edit and delete data sources.',
	'create-semantic-model': 'Create Data Model',
	'create-semantic-model-description': 'Create, view, edit and delete data models.',
	'create-dashboard': 'Create Dashboard',
	'create-dashboard-description': 'Create, view, edit and delete dashboards.',
	'view-dashboard': 'View Dashboard',
	'view-dashboard-description': 'View Dashboards.',
	'create-report': 'Create Report',
	'create-report-description': 'Create, view, edit and delete reports.',
	'view-report': 'View Report',
	'view-report-description': 'View Reports.',
	'schedule-reports': 'Schedule Report/Dashboard',
	'schedule-reports-description': 'Schedule Report/Dashboard.',
	'create-input-form': 'Create Input Form',
	'create-input-form-description': 'Create, view, edit and delete input forms.',
	'view-input-form': 'View Input Form',
	'view-input-form-description': 'View input forms.',
	'view-resource-portal': 'View Resource Portal',
	'view-resource-portal-description': 'View Resource Portal',
	'view-revision': 'View Revision',
	'view-revision-description': 'View revision logs.',
	'allow-sharing': 'Allow Sharing',
	'allow-sharing-description': 'Allow user to share documents to others.',
	'create-web-page': 'Create Webpage',
	'create-web-page-description': 'Allow user to Create Webpage.',
	'assign-manage-user': 'Assign Manage User',
	'assign-manage-user-description': 'Allow organization Administrator to assign Manage User Permission to organization administrator of its sub organization.',
	'manage-user': 'Manage User',
	'manage-user-description': 'Allow organization Administrator to create, edit and delete users within its organization.',
};