export const dashboardPL: LanguageKeyValueMap = {
  'viewDashboard!name': 'View Dashboard',
  'viewDashboard!description': 'Views a dashboard in a dashboard viewer',
  'createDashboard!name': 'Create Dashboard',
  'createDashboard!description': 'Create Dashboard',
  'editDashboard!name': 'Edit Dashboard',
  'editDashboard!description': 'Edits a dashboard',
  'revertDashboardRev!name': 'Revert',
  'revertDashboardRev!description': 'Revert Dashboard',
  'createWith!name': 'Create With...',
  'createWith!description': 'Create a new dashboard based on current file',
  untitled: 'Untitled',
  referencedDataDocuments: 'Referenced Data Document',
  requestFailed: 'Request Failed',
  revertSuccess: 'Dashboard Reverted Successfully',
  revertFailed: 'Dashboard Reverted Failed',
};
