export const profileEditorEN: LanguageKeyValueMap = {
	ProfileSetting: 'Profile Setting',
	PersonalInformation: 'Personal Information',
	Preference: 'Preference',
	ChangePassword: 'Change Password',
	Organization: 'Organization',
	Save: 'Save',
	Cancel: 'Cancel',
	Close: 'Close',
	Reset: 'Reset',
	Apply: 'Apply',
	Email: 'Email',
	Phone: 'Mobile Phone',
	FirstName: 'First Name',
	LastName: 'Last Name',
	FullName: 'Full Name',
	OneValuePerLine: '(One value per line)',
	Avatar: 'Avatar',
	AvatarTip: 'Support formats: PNG, JPG, BMP, GIF',
	ChangeAvatar: 'Change Avatar',
	UploadImage: 'Upload Image',
	BigImageTooltip: 'Cannot upload this image. The file is too big. Image sizes are restricted to 5MB.',
	SelectValue: 'select value',
	NullValue: '<empty>',
	ENTheme: 'Document/Resource Portal Theme',
	CNTheme: 'Document Portal Theme',
	SystemTheme: 'System',
	Language: 'Language',
	Global: 'Global',
	DefaultOrganization: 'Default Organization',
	NotSetDefaultOrganization: '(Not Specified)',
	zh: 'Chinese (Simplified)',
	en: 'English',
	'en-gb': 'English (United Kingdom)',
	'zh-TW': 'Chinese (Traditional)',
	pl: 'Polish',
	'theme!Default': 'Default',
	'theme!Light': 'Light',
	'theme!ActiveReports Server': 'Orange',
	'theme!Blue': 'Blue',
	'theme!Red': 'Red',
	'theme!Forest': 'Forest',
	'theme!Dark Forest': 'Dark Forest',
	'theme!Green': 'Green',
	'theme!Warm Light': 'Warm Light',
	'theme!Minimal Blue': 'Minimal Blue',
	OldPassword: 'Old Password',
	NewPassword: 'New Password',
	NewPasswordConfirm: 'Confirm New Password',
	IncorrectOldPasswordToolTip: 'Old password is incorrect.',
	WeakNewPasswordToolTip: 'Password must be at least 8 characters in length, contain at least 1 lowercase letter, 1 uppercase letter and 1 number.',
	PasswordMatchErrorToolTip: 'The two passwords you entered did not match.',
	PasswordIsBlank: 'Password cannot only contain whitespace charaters',

	OpenErrorCaption: 'Opening profile editor failed',
	OpenErrorContent: 'Cannot open profile editor',
	PersonalInformationLoadErrorCaption: 'Loading personal information failed',
	PersonalInformationLoadErrorContent: 'Cannot load personal information',
	PersonalInformationLoadCustomizePropertiesErrorCaption: 'Loading customize properties failed',
	PersonalInformationLoadCustomizePropertiesErrorContent: 'Cannot load customize properties',
	PersonalInformationSaveErrorCaption: 'Saving personal information failed',
	PersonalInformationSaveErrorContent: 'Cannot save personal information',
	PersonalInformationUpdateAvatarErrorCaption: 'Changing avatar failed',
	PersonalInformationUpdateAvatarErrorContent: 'Cannot change avatar',
	PreferenceSaveErrorCaption: 'Saving preference failed',
	PreferenceSaveErrorContent: 'Cannot save preference',
	PreferenceSaveSuccessCaption: 'Preference saved successfully',
	PreferenceSaveSuccessContent: 'Your setting will be applied after close this dialog',
	ThemeLoadErrorCaption: 'Loading theme list failed',
	ThemeLoadErrorErrorContent: 'Cannot load theme list',
	ChangePasswordSaveErrorCaption: 'Change password failed',
	ChangePasswordSaveErrorContent: 'Cannot change password',
	ChangePasswordSuccessCaption: 'Change password successfully',
	ChangePasswordSuccessContent: 'Change password successfully',
	OrganizationLoadErrorCaption: 'Loading organization list failed',
	OrganizationLoadErrorContent: 'Cannot load organization list',

	Error_002: 'Invalid parameter',
	Error_1002: 'User name can not be empty',
	Error_1003: 'User email can not be empty',
	Error_1009: 'Cannot find the current user personal information',
	Error_1024: 'User mobile already exists',
	Error_1025: 'Invalid email address',
	Error_1026: 'Can not modify user password',
	Error_1034: 'Avatar content can not be empty',

	customTheme: 'Custom Theme',
};
