export const portalEN: LanguageKeyValueMap = {
	true: 'True',
	false: 'False',
	alTurnOnAuditing: 'Turn on Auditing',
	alStoreDays: 'Days to store auditing',
	alProvider: 'Provider',
	alOpenAdvancedOption: 'Use Connection String',
	alConnectionString: 'Connection string',
	alSqlServerServerName: 'Host',
	alSqlServerPort: 'Port',
	alSqlServerDatabaseName: 'Database name',
	alSqlServerAuthentication: 'Authentication',
	alWindowsAuthentication: 'Windows',
	alServerAuthentication: 'Server',
	alSqlServerUserName: 'User name',
	alSqlServerPassword: 'Password',
	alMySqlServerName: 'Host',
	alMySqlPort: 'Port',
	alMySqlDatabaseName: 'Database name',
	alMySqlUserName: 'User name',
	alMySqlPassword: 'Password',
	alOracleServerName: 'Host',
	alOraclePort: 'Port',
	alOracleServiceName: 'Service name',
	alOracleUserName: 'User name',
	alOraclePassword: 'Password',
	alPostgresHost: 'Host',
	alPostgresPort: 'Port',
	alPostgresDatabaseName: 'Database name',
	alPostgresUserName: 'User name',
	alPostgresPassword: 'Password',
	alTest: 'Test',
	alConnection: 'Connect',
	alCreateDatabaseTitle: 'Create database',
	alCreateDatabaseQueryMessage: 'Database does not exist. Do you want to create database?',
	alCreateDatabaseCorrectMessage: 'Create database successfully',
	alCreateDatabaseErrorMessage: 'Failed to create database',
	alCreateTableTitle: 'Create table',
	alCreateTableQueryMessage: 'The audit log tables do not exist in database. Do you want to create tables?',
	alCreateTableCorrectMessage: 'Create tables successfully',
	alCreateTableErrorMessage: 'Failed to create tables',
	alConnectionTitle: 'Connection result',
	alConnectionCorrect: 'Connect successfully',
	alConnectionError: 'Table structure error in the database. Please change database',
	alTestTitle: 'Test result',
	alTestCorrect: 'Test successfully',
	alTestDatabaseInexistence: 'Test failed. Database does not exist',
	alTestTableSchemaError: 'Test failed. Table structure error in the database',
	alTestTableInexistence: 'Test failed. Audit log tables do not exist in database',
	alSaveFailTitle: 'Save failed',
	alSaveFailContent: 'Database config error. Please make sure the connection is successful before saving',
	alAddBuiltInDocumentSuccessTitle: 'Audit log datasource and datasets are created successfully',
	alAddBuiltInDocumentSuccessContent: 'Audit log datasource and datasets are created successfully',
	alAddBuiltInDocumentErrorTitle: 'Create the audit log documents failed',
	alAddBuiltInDocumentErrorContent: 'Create the audit log documents failed. You can create them by yourself',
	alUpdateBuiltInDocumentErrorTitle: 'Update the audit log documents failed',
	alUpdateBuiltInDocumentErrorContent: 'Update the audit log documents failed. You can update theme by yourself',
	alCreateBuiltInDocumentTooltipText: 'Audit log is enabled. Click the Create option below to generate built in Audit log datasource and datasets',
	alCreateBuiltInDocumentTooltipButton: 'Create ...',
};
