export const portalResourceES: LanguageKeyValueMap = {
	'createTheme!name': 'Create Theme',
	'createTheme!description': 'Create Theme',
	'modifyTheme!name': 'Edit...',
	'modifyTheme!description': 'Edit this theme',
};

export const shareResourceES: LanguageKeyValueMap = {

	// common
	ThemeDesigner: 'Theme Designer',
	Save: 'Save',
	Close: 'Close',
	Untitled: 'Untitled',
	Apply: 'Apply',
	Cancel: 'Cancel',
	Preview: 'Preview',
	Yes: 'Yes',
	No: 'No',
	'create-theme!title': 'Create Theme',
	'edit-theme!title': 'Edit Theme',

	// recommend theme
	recommendTitle: 'Start from a sample theme',

	// designer modal
	loadThemeError: 'Load theme failed',
	updateThemeError: 'Update theme failed',
	addThemeError: 'Add theme failed',
	Confirmation: 'Confirmation',
	CloseThemeDesignerConfirm: 'Do you want to leave theme designer and discard the changes?',
	Name: 'Name',
	Description: 'Comment',
	ThemeSaveError: 'Theme save failed',
	PleaseInputName: 'Please input theme name.',
	ThemeNameOnlySapcesError: 'The theme name is invalid. Please do not use spaces only as theme name.',
	ThemeNameError: 'The theme name is invalid. Please do not use restricted symbols < > \ : ? * / | " and do not use . (dot) as the first symbol in the theme name.',

	// Visual Designer
	colorsSetting: 'Colors Settings',
	fontsSetting: 'Fonts Settings',
	majorFont: 'Major Font',
	minorFont: 'Minor Font',
	accent1: 'Accent1',
	accent2: 'Accent2',
	accent3: 'Accent3',
	accent4: 'Accent4',
	accent5: 'Accent5',
	accent6: 'Accent6',
	dark1: 'Dark1',
	dark2: 'Dark2',
	light1: 'Light1',
	light2: 'Light2',
	hyperlink: 'Hyperlink',
	hyperlinkFollowed: 'Hyperlink Followed',
	scrollbarThumb: 'Scrollbar Thumb',
	scrollbarTrack: 'Scrollbar Track',
	majorFontFamily: 'Font Family',
	minorFontFamily: 'Font Family',
	majorFontStyle: 'Style',
	minorFontStyle: 'Style',
	majorFontSize: 'Font Size',
	minorFontSize: 'Font Size',
	majorFontWeight: 'Weight',
	minorFontWeight: 'Weight',
	FontStyleNormal: 'Normal',
	FontStyleItalic: 'Italic',
	FontStyleOblique: 'Oblique',
	FontWeightNormal: 'Normal',
	FontWeightBold: 'Bold',
	FontWeightBolder: 'Bolder',
	FontWeightLighter: 'Lighter',

	err_300000: 'Unexpected error occurs, error message: {{message}}',
	err_300001: 'Document with name "{{Title}}" already exists.',
	err_300002: 'Document is referred by other documents.',
	err_300003: 'Access denied.',
	err_300004: 'Invalid parameter detected.',
	err_300005: 'Document was removed.',
	err_300006: 'Document not found.',
	err_300007: 'Document name can not be empty.',
};
