export const dashboardES: LanguageKeyValueMap = {
  'viewDashboard!name': 'View Dashboard',
  'viewDashboard!description': 'Views a dashboard in a dashboard viewer',
  'createDashboard!name': 'Create Dashboard',
  'createDashboard!description': 'Create Dashboard',
  'editDashboard!name': 'Edit Dashboard',
  'editDashboard!description': 'Edits a dashboard',
  'revertDashboardRev!name': 'Revert',
  'revertDashboardRev!description': 'Revert Dashboard',
  'createWith!name': 'Create With...',
  'createWith!description': 'Create a new dashboard based on current file',
  untitled: 'Untitled',
  referencedDataDocuments: 'Referenced Data Document',
  requestFailed: 'Request Failed',
  revertSuccess: 'Dashboard Reverted Successfully',
  revertFailed: 'Dashboard Reverted Failed',
  'requestFullScreen!name': 'Slide Show',
  'requestFullScreen!description': 'Slide Show',
  'caching!name': 'CACHING',
  allowCachingSetting: 'Allow Caching',
  allowCachingSettingNo: 'No',
  allowCachingSettingYes: 'Yes',
  cachingAgeSetting: 'Caching Interval',
  cachingIntervalSetting: 'Caching Interval Unit',
  cachingIntervalSecond: 'Second',
  cachingIntervalMinute: 'Minute',
  cachingIntervalHour: 'Hour',
  cachingIntervalDay: 'Day',
  cachingIntervalWeek: 'Week',
  cachingIntervalMonth: 'Month',
  cachingIsDisabledLabel: 'No query cache',
  updateTemplateListError: 'Error updating list',
  saveCachingSettingsError: 'Error occured on saving caching settings',
  'openPublishedDesign!name': 'Open Published Design...',
  'openPublishedDesign!description': 'Open published design of this dashboard as read-only',
};
