export const accountEN = {
	// common
	Add: 'Add',
	Edit: 'Edit',
	Save: 'Save',
	Cancel: 'Cancel',
	Home: 'Home',
	Delete: 'Delete',
	Remove: 'Remove',
	DeleteConfirm: 'Delete Confirm',
	Yes: 'Yes',
	No: 'No',
	All: 'All',
	MoveUp: 'Move Up',
	MoveDown: 'Move Down',
	SearchText: 'search text',
	Enabled: 'Enabled',
	Error: 'Error',
	Close: 'Close',
	More: 'More',

	Username: 'Username',
	Roles: 'Roles',
	Organizations: 'Organizations',
	Locked: 'Locked',
	Users: 'Users',
	SelectValue: 'select value',
	UnlockUser: 'Unlock User',
	UnlockUserConfirm: 'Do you want to unlock user "{{user}}" ?',
	Settings: 'Settings',

	// Generate token
	gtUser: 'User',
	gtPassword: 'Password',
	gtAvatarMenu: 'Hide avatar menu',
	gtWelcomeScreen: 'Hide welcome screen',
	gtGenerateToken: 'Generate Token',
	gtToken: 'Token',
	gtTitle: 'Title',
	gtDescription: 'Description',
	gtOrgPath: 'Organization Path',
	gtCreatedTime: 'Created Time',
	gtTokenList: 'Tokens',
	gtIntegratePortalUrl: 'Integrate Portal URL',
	gtIntegrateAdminPortalUrl: 'Integrate Admin Portal URL',
	gtIntegrateResourcePortalUrl: 'Integrate Resource Portal URL',
	invalid_username_or_password: 'Invalid user or password',
	error_description_default: 'Failed to get token, maybe it\'s due to user disabled or deleted.',
	gtRevoke: 'Revoke token',
	'gtRevoke!btn': 'Revoke',
	gtGenerateTokenSuccess: 'Token generated successfully',
	gtRevokeTokenSuccess: 'Token revoked successfully',
	gtGenerateUrl: 'Generate integration url...',
	gtGenerateUrlTitle: 'Generate URL',
	gtGetToken: 'Get token',
	gtClipboardError: 'Cannot write data to clipboard',
	gtClipboardSuccess: 'Successfully copied to clipboard',
	gtRevokeToken: 'Revoke Token',
	gtRevokeTokenConfirmMessage: "Do you want to revoke token '{{title}}'?",
	gtCopyUrl: 'Copy URL',
	gtCopyOfflineLicenseString: 'Copy Offline license string',
	gtExpiryTime: 'Expiry Time',
	error_100001: 'Invalid parameter: {{name}}',
	error_100002: 'Unknown error: {{message}}',
	error_100003: 'Integration token not found {{id}}',
	error_100004: 'Revoke token error: {{message}}',
	error_100005: 'Please confirm that the "Portal URI" in "UI Settings" is already provided before you generate the Integration URL.',
	error_100006: 'Request user claims failed.',
	gtExpireTimeInvalid: 'The expiry time is invalid',
	gtExpireTimeLessThanNow: 'The expiry time cannot be less than or equal current time',
	gtState: 'State',
	gtValid: 'Valid',
	gtExpired: 'Expired',

	// Customize properties
	AddProperty: 'Add Property',
	EditProperty: 'Edit Property',
	DeleteProperty: 'Delete Property',
	PropertyName: 'Property Name',
	AvailableValues: 'Available Values',
	AvailableValuesDesc: 'Available Values(One value per line)',
	ShowInList: 'Show In List',
	DeletePropertyConfirmMessage: 'Do you want to delete property "{{property}}" permanently?',
	PropertyNameRequirement: "The max length of customize property name is 64, and it can not contain '<', '>', '/' and '\\'.",
	ContinueUpdate: 'Continue Update?',
	UpdatePropertyConfirm: 'The property values "{{propValues}}" are in use, these values will be cleared if you update the property, do you want to continue?',
	NewPropertyName: 'New property name',
	NoCustomizePropertiesTip: 'No extended properties in the system.To add,please click',
	AllowEdit: 'Allow User To Edit',
	Multivalued: 'Multivalued',
	ShowInProfile: 'Display In User Profile Page',
	MultivaluedChangedWarning: 'Modifying the value of multivalued property of the custom property will cause the value of the custom property of all roles in the system to change, please be careful!',

	// Locked  user management
	NoLockedUserTip: 'No locked users in the system.',

	// Concurrence management
	Ban: 'Ban User',
	IpAddress: 'IP Address',
	UserAgent: 'UserAgent',
	loginDate: 'Login Date',
	NoLoginUserTip: 'No Logged-in user in the system',

	// License
	RegistrationDate: 'Registration Date',
	LicenseKey: 'LicenseKey',
	ServerGeneratedInfo: 'ServerGeneratedInfo',
	ExpiryDate: 'Expiry Date',
	LicenseInfo: 'License Info',
	Register: 'Register',
	Deregister: 'Deregister',
	Refresh: 'Refresh',
	Summary: 'Summary',
	DeregisterConfirm: 'Confirm Licence Deregister',
	DeregisterConfirmMessage: 'Are you sure you want to deregister license "{{license}}"?',
	Succeed: "Success.",
	RefreshConfirm: 'Confirm License Refresh',
	RefreshConfirmMessage: 'Are you sure you want to refresh license "{{license}}"?',
	Available: 'Available',
	Included: 'Included',
	Unlimited: 'Unlimited',
	NoExpire: 'Never Expire',
	Report: 'Report concurrence count',
	Report_Module: 'Report Module',
	Report_Documents: 'Report documents count',
	Dashboard: 'Dashboard concurrence count',
	Dashboard_Module: 'Dashboard Module',
	Dashboard_Documents: 'Dashboard documents count',
	Datasource: 'Datasource count',
	YouAreOffline: 'Could not connect to net, you are in offline mode, pleaset contact us.',
	OfflineLicenseString: 'Offline license string:',
	OfflineLicensePathBaseUS: 'https://wyn-licensing.grapecity.com/',
	OfflineRegisterLineUS1: 'Wyn Server could not connect to internet.To register license in offline mode follow the below steps:',
	OfflineRegisterLineUS2_1: '1. Open our offline license registration ',
	OfflineRegisterLineUS2_2: 'page',
	OfflineRegisterUS_Address: 'activation',
	OfflineRegisterLineUS2_3: ' on a machine with internet access and use the offline license string displayed above to generate a licence registration string from server.',
	OfflineRegisterLineUS3: '2. Paste the string generated from previous step in ServerGeneratedInfo field and click Register button.',

	OfflineRefreshLineUS1: 'Wyn Server could not connect to internet.To refresh license in offline mode follow the below steps:',
	OfflineRefreshLineUS2_1: '1. Open our offline license refresh ',
	OfflineRefreshLineUS2_2: 'page',
	OfflineRefreshUS_Address: 'refresh',
	OfflineRefreshLineUS2_3: ' on a machine with internet access and use the offline license string displayed above to generate a licence refresh string from server.',
	OfflineRefreshLineUS3: '2. Paste the string generated from previous step in ServerGeneratedInfo field and click refresh button.',

	OfflineDeregisterLineUS1: 'Wyn Server could not connect to internet.To deregister license in offline mode follow the below steps:',
	OfflineDeregisterLineUS2_1: '1. Open our offline license deactivation ',
	OfflineDeregisterLineUS2_2: 'page',
	OfflineDeregisterUS_Address: 'deactivation',
	OfflineDeregisterLineUS2_3: ' on a machine with internet access and use the offline license string displayed above to deregister the licence.',
	OfflineDeregisterLineUS3: '2. Click Close button when license is deactivated successfully.',

	NoLicenseTip: 'The current environment has no product license,click on the top left corner',
	NoLicenseTipTrialInfo: 'The product trial will expire on {{expireDate}}. Click ',
	NoLicenseTipTrialExpireInfo: 'The product trial has expired on {{expireDate}}. Click ',
	NoLicenseTipTrialInfoSuffix: 'to activate a full license.',
	CouldNotRegisterTip: 'Licence key is already registered. Please deregister the existing key to register a new key',
	KeyType: 'Key Type',
	KeyTypeTrial: 'Trial',
	KeyTypePerpetual: 'Perpetual',
	KeyTypeAnnual: 'Annual',
	ExpiredSuffix: '(Expired)',
	VersionExpiredSuffix: '(Version not matched))',

	// System configurations
	UserMapping: 'User Mapping',
	AddProvider: 'Add Provider',
	ProviderName: 'Provider Name',
	Description: 'Description',
	AddSecurityProvider: 'Add Security Provider',
	RemoveSecurityProvider: 'Remove Security Provider',
	RemoveSecurityProviderConfirm: 'Do you want to remove security provider "{{provider}}"?',
	MappingByEmail: 'Mapping Users By Email',
	MappingByMobile: 'Mapping Users By Mobile Number',
	Confirm: 'Confirm',
	MappingByEmailConfirm: `Do you want to mapping all the external users to built-in users by the user's email?`,
	MappingByMobileConfirm: `Do you want to mapping all the external users to built-in users by the user's mobile number?`,
	ConfirmDoIt: 'Confirm do it?',
	ExternalUserId: 'External User Id',
	ExternalUserName: 'External User Name',
	InnerUserName: 'Inner User Name',
	ExternalUserEmail: 'External User Email',
	ExternalUserMobile: 'External User Mobile',

	// Client Management
	AllowedGrantTypes: 'Allowed Grant Types',
	AllowedScopes: 'Allowed Scopes',
	AllowedUris: 'Allowed Uris',
	AccessTokenLifetime: 'Access Token Lifetime',

	// Security Providers and External Providers
	'account_provider_local': 'Built-In Account Provider',
	'account_provider_local_description': 'The built-in account management system provided by local identity service.',
	'account_provider_WeChat4Work': 'Enterprise WeChat',
	'account_provider_WeChat4Work_description': 'The account management system provided by enterprise wechat.',
	'account_provider_AD Security Provider': 'Active Directory',
	'account_provider_AD Security Provider_description': 'Active directory security provider.',
	'account_provider_DingTalk': 'DingTalk',
	'account_provider_DingTalk_description': 'The account management system provided by DingTalk',

	NoSecurityProviderTip: 'You are currently using the built-in account mode for login',
	NoExternalProviderTip: 'Enterprise users are not added currently',
	NoAvailableSecurityProvidersTip: 'There is no any Providers available',

	'ShowPassword': 'Show password',
	'HidePassword': 'Hide password',

	// Security Settings
	EnableStrongPasswordPolicy: 'Enable strong password policy',
	EnableStrongPasswordPolicyDescription: 'The password must contain the following: \n    \u2022 1 uppercase letter\n    \u2022 1 lowercase letter\n    \u2022 1 number\n    \u2022 Length between 8-32 characters\nThe default password policy only requires that the password length be between 1 - 32 characters, and can contain any character. ',
	UserLockedTime: 'User locked time (minutes)',
	UserLockedTimeDescription: 'When a user enters the wrong password more than 5 times consecutively, that user will be locked out. During the locked time, the user cannot login, even with the correct password. You can change the locked time to a different value, or set it to 0 to disable the lock behavior. ',
	AllowUserResetPassword: 'Allow user reset password',
	AllowUserResetPasswordDescription: 'Enable this option allow user to reset his/her password.',

	// Claim Mappings
	ClaimName: 'Claim Name',
	UserPropName: 'User Property Name',
	AddClaim: 'Add Claim',
	DeleteClaim: 'Delete Claim',
	DeleteClaimConfirmMessage: "Do you want to delete user context '{{claim}}'?",
	Create: 'Create',

	// Identity Server User Controller Error Code Range 1000 ~ 2000
	error_1001: 'Invalid PageSize or PageNumber',
	error_1002: 'User name can not be empty.',
	error_1003: 'User email can not be empty.',
	error_1004: 'The password should contain at least 1 uppercase letter, 1 lowercase letter and 1 number, and the length should be between 8 and 32.',
	error_1005: 'User name already exists.',
	error_1006: 'User email already exists.',
	error_1007: 'Role \'{{role}}\' does not exist.',
	error_1008: 'Invalid parameter.',
	error_1009: 'User not found.',
	error_1010: 'User already exists.',
	error_1011: 'Extend property \'{{prop}}\' not found.',
	error_1012: 'Value \'{{value}}\' is invalid for extend property \'{{prop}}\'.',
	error_1013: 'Save data to database failed.',
	error_1014: 'User name can not be modified.',
	error_1015: 'No file found.',
	error_1016: 'No visible spread sheet found.',
	error_1017: 'Invalid user template format.',
	error_1018: 'No user found.',
	error_1019: 'Locked user with id \'{{id}}\' does not exist.',
	error_1020: 'Invalid password.',
	error_1021: 'Invalid security token.',
	error_1022: 'Forbidden ip address.',
	error_1023: 'Language is not supported.',
	error_1024: 'User mobile number can not be empty.',
	error_1025: 'Invalid email address.',

	// Import users error
	error_1100: "Row [{{rowIndex}}]: User id '{{userId}}' already exists.",
	error_1101: "Row [{{rowIndex}}]: User name can not be empty.",
	error_1102: "Row [{{rowIndex}}]: User name '{{userName}}' already exists.",
	error_1103: "Row [{{rowIndex}}]: User email can not be empty.",
	error_1104: "Row [{{rowIndex}}]: User email '{{userEmail}}' already exists.",
	error_1105: "Row [{{rowIndex}}]: User mobile '{{userMobile}}' already exists.",
	error_1106: "Row [{{rowIndex}}]: User password can not be empty.",
	error_1107: "Row [{{rowIndex}}]: Invalid password format. The password must contain at least 8 and less than 32 characters, and contain at least 1 lowercase, 1 uppercase letter and 1 number.",
	error_1108: "Row [{{rowIndex}}]: Invalid creation time '{{creationTime}}'.",
	error_1109: "Row [{{rowIndex}}]: Invalid value '{{value}}' for field 'enabled'.",
	error_1110: "Row [{{rowIndex}}]: Role '{{role}}' does not exist.",
	error_1111: "Row [{{rowIndex}}]: Invalid email address '{{userEmail}}'.",

	// Identity Server Role Controller Error Code Range 2001 ~ 2999
	error_2001: 'Role \'{{name}}\' already exists.',
	error_2002: 'Role name can not conflict with permission name.',
	error_2003: 'Built-in role can not be deleted.',
	error_2004: "Can not update the members of role 'everyone'.",
	error_2005: "Can not remove member 'admin' from role 'administrator'.",
	error_2006: "Can not modify the permissions of role 'administrator'.",
	// Identity Server Claim Mapping Errors
	error_3001: "User context '{{claimName}}' already exists.",
	error_3002: "User context with id '{{claimId}}' does not exist.",
	error_3003: "Customize property '{{propName}}' does not exist.",
	error_3004: "Built-in user context can not be modified.",
	error_3005: "Built-in user context can not be deleted.",
	error_3006: "Invalid claim mapping name. The length of the claim mapping name should be between 1 and 64, and the name can not contains '<', '>', '/', '\\', '$' and some invalid keywords.",
	// Identity Server Custom Property Errors
	error_4001: "Custom property '{{propName}}' already exists.",
	error_4002: "Custom property '{{propName}}' does not exist.",
	error_4003: "Custom property with id '{{propId}}' does not exist.",
	error_4004: "Invalid customize property name. The length of customize property name should be between 1 and 64, and the name can not contains '<', '>', '/', '\\', '$' and some invalid keywords.",
	// Identity Server Tenant Errors
	error_5001: "Tenant name can not be empty.",
	error_5002: "Tenant '{{tenantName}}' already exists.",
	error_5003: "Tenant property name can not be empty.",
	error_5004: "Tenant property '{{tenantPropName}}' already exists.",
	error_5005: "Tenant property '{{tenantPropName}}' is reserved.",
	error_5006: "Tenant from email '{{fromEmail}}' already exists.",

	//LicenseActiveResult
	LicenseOprateResultCode_: "",
	LicenseOprateResultCode_1000: "Unknown Error",
	LicenseOprateResultCode_1001: "Key is invalid.",
	LicenseOprateResultCode_2000: "Activation failed.",
	LicenseOprateResultCode_2001: "Key is disabled.",
	LicenseOprateResultCode_2002: "Key type incorrect.",
	LicenseOprateResultCode_2003: "Exceeds the maxinum activation count.",
	LicenseOprateResultCode_2004: "license is already activated",
	LicenseOprateResultCode_2005: "Key's version did not match current version.",
	LicenseOprateResultCode_2006: "Empty Key",
	LicenseOprateResultCode_2007: "License content is not valid.",
	LicenseOprateResultCode_3000: "Deactivation Failed",
	LicenseOprateResultCode_3001: "Trial license cannot be deactived",
	LicenseOprateResultCode_3002: "Activation info not matched.",
	LicenseOprateResultCode_3011: "Deactive info not match Token",
	LicenseOprateResultCode_3012: "Deactive info not match machine",
	LicenseOprateResultCode_3013: "Deactive info not match computerId",
};

export const portalEN = {
	'shortcut-org!description': "",
	'shortcut-org!props!text': "Organizations",
	'shortcut-org!title': "Organizations Shortcut",
	'shortcut-user!description': "",
	'shortcut-user!props!text': "Users",
	'shortcut-user!title': "Users Shortcut",
	'shortcut-role!description': "",
	'shortcut-role!props!text': "Roles",
	'shortcut-role!title': "Roles Shortcut",
	'shortcut-locked!description': "",
	'shortcut-locked!props!text': "Locked",
	'shortcut-locked!title': "Locked Shortcut",
	'shortcut-license!description': "",
	'shortcut-license!props!text': "License",
	'shortcut-license!title': "License Shortcut",
	'account-management-generate-token!title': 'Generate Token',
	'account-management-generate-token!description': 'Generate Token',
}

export const cgridEN = {
	cgridMore: 'More'
}