export const uploadEN: LanguageKeyValueMap = {
	// Upload
	naUploading: 'Uploading...',
	naCommit: 'Commit',
	naCancel: 'Cancel',
	naClose: 'Close',
	naReadyToCommit: 'Ready To Commit',
	naInvalidFiles: 'Invalid',
	naUnresolvedFiles: 'Unresolved',
	naReferenceUnresolvedFiles: 'Missing reference',
	naUploading2: 'Uploading',
	naAlreadyExists: 'Already exist',
	ufiBtnTitleKeepBoth: 'Keep both documents',
	ufiBtnTitleOverwrite: 'Overwrite document',
	ufiBtnTitleUpgrade: 'Upgrade document',
	ufiBtnTitleOverwriteSection: 'Overwrite documents',
	usErrorTextSessionError: 'Upload session error',
	usErrorTextValidationError: 'Validation Error',
	usErrorTextValidationErrorDetails: 'We were unable to get validation status. Sorry',
	usErrorTextUploadCommitError: 'Upload Error',
	usErrorTextUploadCommitErrorDetails: 'We were unable to commit. Sorry',
	usErrorTextCancellationError: 'We couldn\'t cancel uploading of this file. Sorry',
	usWarning: 'Upload warning',
	BatchSetActor: 'When uploading files already exist:',
	OperateIndividually: 'Operate Individually',
	OverwriteAll: 'Overwrite All',
	KeepBothAll: 'Keep Both For All Documents',
	Collapse: 'Collapse',
	Expand: 'Expand',
	warning_1: 'Font Document ({{title}}) real font name of the uploaded font file cannot be automatically recognized.',

	// Drop Zone
	dzDragDrop: 'Drag & Drop',
	dzFiles: 'Files',
	dzClickToSelect: 'or click here to select',
	dzUpload: 'Upload',
};
