export const portalES: LanguageKeyValueMap = {
  'shortcut-dashboards!description': '',
  'shortcut-dashboards!props!text': 'Dashboards',
  'shortcut-dashboards!title': 'Dashboards Shortcut',

  'dashboardsConfiguration!title': 'Dashboards Settings',
  'dashboardsConfiguration!description': 'Configure Dashboards',
  'dashboardsConfiguration!containerFilterScope': 'Container Filter Scope',
  'dashboardsConfiguration!containerFilterScope!Container': 'Container',
  'dashboardsConfiguration!containerFilterScope!Global': 'Global',
  'dashboardsConfiguration!maxAggregatedDataPoints': 'Maximum Aggregated Data Points',
  'dashboardsConfiguration!enableDeveloperMode': 'Enable Developer Mode',
  'dashboardsConfiguration!defaultViewer': 'Default Viewer',
  'dashboardsConfiguration!defaultViewer!standard': 'Standard',
  'dashboardsConfiguration!defaultViewer!lite': 'Lite',
  'dashboardsConfiguration!notInIframeByDefaultForCertifiedVisuals': 'Not In iframe By Default For Certified Visuals',
  'dashboardsConfiguration!clickAction': 'Click Action',
  'dashboardsConfiguration!clickAction!showTooltip': 'Show Tooltip',
  'dashboardsConfiguration!clickAction!none': 'None',
  'dashboardsConfiguration!clickAction!keep': 'Keep',
  'dashboardsConfiguration!clickAction!exclude': 'Exclude',
  'dashboardsConfiguration!clickAction!drillTo': 'Drill Down',
  'dashboardsConfiguration!clickAction!jumpTo': 'Jump',
  'dashboardsConfiguration!contextMenuActions': 'Context Menu Actions',
  'dashboardsConfiguration!contextMenuActions!keep': 'Keep',
  'dashboardsConfiguration!contextMenuActions!exclude': 'Exclude',
  'dashboardsConfiguration!contextMenuActions!drillTo': 'Drill Down',
  'dashboardsConfiguration!contextMenuActions!jumpTo': 'Jump',
  'dashboardsConfiguration!enablePdfExport': 'Enable PDF Export',
  'dashboardsConfiguration!showWizard': 'Show Visualization Wizard For New Dashboard',
  selectAll: '(All)',
  selectNone: '(None)',
};
