export const portalES: LanguageKeyValueMap = {
	'nodeManagement!title': 'Node Management',
	'nodeManagement!description': 'Node Management',
	nodes: 'Nodes',
	globalSettings: 'Global Settings',
	getNodeFailed: 'Get Nodes Failed',
	addNode: 'Add Node',
	removeNode: 'Delete',
	'removeNode!title': 'Delete Node',
	'removeNode!description': 'Do you want delete the current node?',
	nodeName: 'Node Name',
	nodeDescription: 'Description',
	nodeStatus: 'Node Status',
	up: 'Online',
	down: 'Offline',
	nodeHost: 'Host',
	nodePort: 'Port',
	nodeType: 'Node Type',
	'nodeType!primary': 'Primary Node',
	'nodeType!secondary': 'Secondary Node',
	'nodeType!client': 'Client Node',
	downloadUrl: 'Download URL',
	download: 'Download',
	copy: 'Copy',
	token: 'Token',
	error_valueNotBeEmpty: 'Value should not be empty.',
	error_HostIsInvalid: 'Invalid IP',
	error_PortIsInvalid: 'Invalid Port',
	error_InvalidUrl: 'Invalid URL',
	nodeBasicInfo: 'Basic Information',
	nodeSettings: 'Settings',
	installHelpTitle: 'How to install?',
	save: 'Save',
	cancel: 'Cancel',
	'yes': 'Yes',
	'close': 'Close',
	serviceName: 'Service Name',
	serviceVersion: 'Version',
	serviceStatus: 'Status',
	serviceInfos: 'Service Information',
	'serviceName_worker': 'Report Worker',
	'serviceName_cotworker': 'Cot Worker',
	'serviceName_dashboardworker': 'Dashboard Worker',
	'serviceName_server': 'Server',
	'serviceName_analysisdbprimarynode': 'AnalysisDB Primary Node',
	'serviceName_analysisdbservice': 'AnalysisDB Service',
	'serviceName_schedulerservice': 'Scheduler Service',
	'serviceStatus_starting': 'Running',
	'serviceStatus_running': 'Running',
	'serviceStatus_stopped': 'Stopped',
	'serviceStatus_notinstalled': 'Not Installed',
	'serviceStatus_uninstall': 'uninstall',
	'runCommandLine': 'Run command line as administrator:',
	'step1!description1': 'Step 1: Download and install',
	'step1!description2': '.NET Core Runtime',
	'step1!description3': '(Recommend version 3.1.7)',
	'step2!description1': 'Step 2: Click and Download',
	'step2!description2': 'binary zip',
	'step2!description3': 'file',
	'step3!description': 'Step 3: Execute shell script.',
	stop: 'Stop',
	start: 'Start',
	install: 'Install',
	uninstall: 'Uninstall',
	identityUrl: 'Identity Server URL',
	logLevel: 'Log Level',
	primaryNodeHost: 'Primary Node Host',
	primaryNodePort: 'Primary Node Port',
	success: 'Success',
	failed: 'Failed',
	warning: 'Warning',
	Name_Had_Be_Existed: 'Name existed.',
	Member_Is_Not_Found: 'Node is offline.',
	Request_Sent_Successfully: 'Request sent successfully.',
	Start_Service_Failed: 'Start service failed.',
	Stop_Service_Failed: 'Stop service failed.',
	Install_Service_Failed: 'Install service failed.',
	Uninstall_Service_Failed: 'Uninstall service failed.',
	Operation_Is_Not_Supported: 'Invalid operation for current node.',
	Invalid_Secret_Key: 'Invalid secret key.',
	Install_Server_Client_Error: 'Create server client failed.',
	UnInstall_Server_Client_Error: 'Remove server client failed.',
	Invalid_Server_Related_Configuration: 'Invalid server configurations. Please follow the steps in Documentation to configure them.',
	Invalid_Cot_Worker_Configuration: 'Invalid COT worker configuration: "{{key}}". Please follow the steps in Documentation to configure it.',
	Invalid_Dashboard_Worker_Configuration: 'Invalid Dashboard worker configuration: "{{key}}". Please follow the steps in Documentation to configure it.',
	Invalid_Reporting_Worker_Configuration: 'Invalid Report worker configuration: "{{key}}". Please follow the steps in Documentation to confiture it.',
	Save_Success: 'Save successfully',
	Cant_Get_Data_From_Primary: 'Can not get data from the primary node. Please make sure the primary node is alive.',
	Cannot_Delete_Node: 'Can not delete the node with {{services}} installed.',
	primaryNodeNotInited: 'The secondary node can not connect to primacy node due to one of the following reasons: \n1. The host of your primary node should be not listening on \'127.0.0.1\' or \'localhost\'.\n2. The identity url is not public. It should be not listening on \'127.0.0.1\' or \'localhost\'.',
	settings_changed: 'Save Settings',
	'settings_changed!description1': 'Do you want save your changes? All services of the current node will be restarted.',
	'settings_changed!description2': 'Do you want save your changes? All services of the all nodes will be restarted.',
	'EnableMultipleServers!title': 'Install Server',
	'EnableMultipleServersTip': 'Please follow the steps in Documentation to enable multiple servers mode.',

	Error_Node_50000: 'The primary node IP is unavailable.',

};
