export const schedulingES: LanguageKeyValueMap = {

	// Global
	taskStatusEnabled: 'Enabled',
	taskStatusDisabled: 'Disabled',

	// Tabs
	tasksTabCaption: 'Tasks',
	tasksTabDescription: 'Scheduled tasks for the document',

	historyTabCaption: 'History',
	historyTabDescription: 'Scheduled task execution history',

	// Tasks Tab
	tasksTabHeader: 'Scheduled Tasks',
	tasksTabNoTasks: 'There are no scheduled tasks for this document',
	tasksTabBtnAddTask: 'Add Task',

	// Task Item
	taskItemRunBtnTitle: 'Run Task',
	taskItemMenuBtnTitle: 'Actions',
	taskItemMenuEnableText: 'Enable',
	taskItemMenuEnableTitle: 'Enable Task',
	taskItemMenuDisableText: 'Disable',
	taskItemMenuDisableTitle: 'Disable Task',
	taskItemMenuEditText: 'Edit',
	taskItemMenuEditTitle: 'Edit Task',
	taskItemMenuDeleteText: 'Delete',
	taskItemMenuDeleteTitle: 'Delete Task',
	taskItemTextNextRun: 'Next run:',
	taskItemTextManually: 'Manually',
	taskItemTextNever: 'Never',

	// Task Editor
	taskNoScheduleTemplateTip: 'no schedule template',
	taskEditorHeaderDetails: 'Details',
	taskEditorInputPlaceholderDescription: 'Task description',
	taskEditorLabelExecution: 'Execution',
	taskEditorExecutionManual: 'Manual',
	taskEditorExecutionOneTime: 'One-Time',
	taskEditorExecutionScheduled: 'Scheduled',
	taskEditorLabelStart: 'Start',
	taskEditorBtnCreateText: 'Create Task',
	taskEditorBtnUpdateText: 'Update Task',
	taskEditorBtnCancelText: 'Cancel',
	oneTimeStartTimeLimit: 'The start time cannot be set to any time less than 5 minutes from now',
	oneTimeStartTimeLimitTitle: 'Invalid time',
	taskEditorDescriptionError: 'Task description should not be empty',
	fileNameError: 'File name should not be empty',
	fullPathError: 'File path should not be empty',
	// Recurrence Editor
	recEditorCloneFromTemplate: 'Use Template',
	recEditorChooseTemplate: 'Choose Template',
	recEditorTemplateHasBeenDeleted: 'Template has been deleted',
	recEditorHeaderRepeat: 'Repeat',
	recEditorLabelStart: 'Start',
	recEditorLabelEnd: 'End',
	recEditorPlaceholderNoEndDate: 'No End Date',
	recEditorDailyEditor: 'Daily',
	recEditorWeeklyEditor: 'Weekly',
	recEditorMonthlyEditor: 'Monthly',

	// Daily Editor
	dailyEditorTextAt: 'At {{time}}',
	dailyEditorTextEvery: 'Every',
	dailyEditorTextUnits: 'hour(s)',

	// Weekly Editor
	weeklyEditorTextEvery: 'Every',
	weeklyEditorTextUnits: 'week(s)',

	// Monthly Editor
	monthlyEditorTextEvery: 'Every',
	monthlyEditorTextUnits: 'month(s)',
	monthlyEditorTextOnDay: 'On day',
	monthlyEditorTextOnDayUnits: '',
	monthlyEditorTextOnTheLast: 'On the last',
	monthlyEditorTextOnTheFirst: 'On the first',
	monthlyEditorTextLastDay: 'Day',
	monthlyEditorTextLastWeekday: 'Weekday',

	// Delivery Editor
	delEditorHeader: 'Delivery',
	delEditorMenuEmail: 'Email',
	delEditorMenuLocal: 'Local Storage',
	delEditorMenuWFS: 'File Share',

	delEditorLocalStoreForever: 'Store forever',
	delEditorLocalStoreUntil: 'Store until...',
	delEditorLocalDeleteAfter: 'Expiry Duration...',
	delEditorLocalTextOnDayUnits: 'Day(s)',
	delEditorLocalAllowAnonymous: 'Allow anonymous',

	delEditorWFSLabelFileName: 'File Name',
	delEditorWFSLabelPath: 'Path',
	delEditorWFSLabelOverwrite: 'Overwrite existing',
	delEditorWFSLabelUser: 'User',
	delEditorWFSLabelPassword: 'Password',

	delEditorMailStoreForever: 'Store forever',
	delEditorMailStoreUntil: 'Store until...',
	delEditorMailDeleteAfter: 'Expiry Duration...',
	delEditorMailAllowAnonymous: 'Allow anonymous',

	expiryTimeUnitHour: 'Hours',
	expiryTimeUnitDay: 'Days',
	expiryTimeUnitWeek: 'Weeks',
	expiryTimeUnitMonth: 'Months',
	expiryTimeUnitYear: 'Years',

	delEditorMailLabelEmailTo: 'Email To',
	delEditorMailLabelEmailToLabel: 'Please enter email to',
	delEditorMailLabelEmailToIsInvalid: 'Email format is invalid',
	delEditorMailLabelInvalidDomainTip: 'Invalid Email Domain',
	delEditorMailLabelReplyTo: 'Reply To',
	delEditorMailLabelReplyToLabel: 'Please enter reply to',
	delEditorMailLabelSubject: 'Subject',
	delEditorMailLabelSubjectToolTip: 'You can reference any parameter in the subject by entering a question mark (?) followed by the parameter\'s name.The report\'s name can be referenced with the special placeholder &ReportName. The time the report was run can be referenced with the special placeholder &ExecutionTime.',
	delEditorMailLabelBody: 'Body',
	delEditorMailLabelBodyToolTip: 'You can reference any parameter in the message body by entering a question mark (?) followed by the parameter\'s name.The report\'s name can be referenced with the special placeholder &ReportName. The time the report was run can be referenced with the special placeholder &ExecutionTime. If attachment type is \'Send Report as Body\', the attachment in the email body can be referenced with the special placeholder &ExportResult.',
	delEditorMailLabelAttachmentType: 'Attachment Type',
	delEditorMailAttachmentFile: 'File Attachment',
	delEditorMailAttachmentLink: 'Download Link',
	delEditorMailAttachmentBody: 'Send Report as Body',
	delEditorMailSubject: 'Scheduled Report',
	delEditorMailBody: 'Here is the &ReportName report. This report was run at &ExecutionTime. The report is linked or attached below. &Link &ExportResult',

	// Reporting Editor
	reportingEditorHeaderExportFormat: 'Export Format',
	reportingEditorAdvancedExportSettings: 'Advanced Settings',
	reportingEditorHeaderParameters: 'Parameters',
	reportingEditorParametersStateInitializing: 'Initializing...',
	reportingEditorParametersStateValidating: 'Validating...',
	reportingEditorParametersStateValid: 'Valid Parameters',
	reportingEditorParametersStateinvalid: 'Invalid Parameters',
	reportingEditorTextNoParameters: 'report has no parameters',

	// Job Editor Saga
	jeSagaQueueErrorTaskFailed: 'Task Failed',
	jeSagaQueueErrorExecFailed: 'Unable to execute task',
	jeSagaQueueErrorNoWorkers: 'No workers available',
	jeSagaQueueErrorUnknown: 'Unknown Error',

	jeSagaTextJobEditorError: 'Job Editor Error',
	jeSagaTextParametersError: 'Unable to get report parameters',
	jeSagaTextParameterValuesError: 'Unable to get parameter values',

	jeSagaFail: 'Reporting Job Editor: Unknown Error',

	// History Tab
	histTabHeaderRunning: 'Running',
	histTabHeaderResults: 'Results',
	histTabNoHistory: 'There is no task history for this document',

	// History & Job Items
	hiStatusCancelled: 'Cancelled',
	hiStatusFailed: 'Failed',
	hiStatusCompleted: 'Completed',
	hiStatusAccomplished: 'Completed',
	jiStatusQueued: 'Queued',
	jiStatusRunning: 'Running',

	hiTitleDownload: 'Download',
	hiTitleShowError: 'Show error details',
	hiTitleShowWarn: 'Show warning details',

	// Security Error Message
	securityErr_10001: '[Security Error] Discovery Client Retrieves discovery document error.',
	securityErr_10002: '[Security Error] Get discovery document error.',
	securityErr_10003: '[Security Error] Request refresh token error',
	securityErr_10004: '[Security Error] Get access token error: \n1, The organization in which the task is created does not exist.\n2, The user who creates the task is not in the specified organization.\n3, The user who creates the task does not exist.',

	// Execution Error Message
	executionErr_10001: '[Execution Error] Unknown cot task status.',
	executionErr_10002: '[Execution Error] Cot task not found.',
	executionErr_10003: '[Execution Error] Cot task not created.',
	executionErr_10004: '[Execution Error] An IO error occurred: {{ errorMessage }}.',
	executionErr_11001: '[Execution Error] The specified directory is not found.',
	executionErr_11002: '[Execution Error] You don\"t have permission to access datasource.',
	executionErr_11003: '[Execution Error] File: {{ errorUsing }} is being used and file: { { errorDestroy } } can\'t be extracted,please check the file format.',
	executionErr_11004: '[Execution Error] File: {{ errorUsing }} is being used.',
	executionErr_11005: '[Execution Error] File: {{ errorDestroy }} can\'t be extracted, please check the file format or the file password.',
	executionErr_11006: '[Execution Error] Overwrite operation does not support multiple files.',
	executionErr_11007: '[Execution Error] Cannot get correct response from refresh cot api.',
	executionErr_12001: '[Execution Error] RefreshCot exception: {{errorMessage}}.',
	executionErr_13001: '[Execution Error] {{errorMessage}}.',

	// Deployment Error Message
	deploymentErr_10001: '[Deployment Error] Email domain error: Recipients email address outside your organization.',
	deploymentErr_10002: '[Deployment Error] Mailing error: {{errorMessage}}.',
	deploymentErr_10003: '[Deployment Error] Mailing error: {{errorMessage}}.',
	deploymentErr_10004: '[Deployment Error] Mailing error: {{errorMessage}}.',
	deploymentErr_10005: '[Deployment Error] Mailing error: {{errorMessage}}.',
	deploymentErr_10006: '[Deployment Error] File share error: {{errorMessage}}',
	deploymentErr_10007: '[Deployment Error] Result expiration date have already passed.',
	deploymentErr_10008: '[Deployment Error] Not delivered because the report is empty.',

	// GraphQl Error Message
	taskErr_30001: 'Permission Required.',
	taskErr_30002: 'Document not found.',
	taskErr_30003: 'Administrator or document owner required.',
	taskErr_30004: 'Failed to create task - task is invalid.',
	taskErr_30005: 'Failed to create task - Store until is earlier than start time.',
	taskErr_30006: 'Failed to create task - recipients email address outside your organization.',
	taskErr_30007: 'Task <{{taskId}}> not found.',
	taskErr_30008: 'Invalid task data provided.',
	taskErr_30009: 'Task <{{taskId}}> is invalid.',
	taskErr_30010: 'Datasorce <{docEnv.Value.Title}> is unable to append data.',
	taskErr_30011: 'Location <{taskInfoDto.Location }> not exists.',
	taskErr_30012: 'Invalid operation : <{taskInfoDto.OperationType}>.',
	taskErr_30019: 'Your cannot create or update manual and one time task due to settings by administrator.',
	taskErr_30020: 'Delivery cannot be file share due to settings by administrator.',
	taskErr_30021: 'Portal URI is required when creating tasks for report. Please contact the Administrator',
	taskErr_30022: 'Portal URI is required when creating tasks for data source. Please contact the Administrator.',
	taskErr_30023: 'Portal URI is required when creating tasks for dataset. Please contact the Administrator.',
	taskErr_30024: 'Failed to create task, the current dataset has already created the task in other organization.',

	// SAGA: enable/disable task
	sagaTextErrorUpdatingTaskList: 'Error updating task list',
	sagaTextErrorGettingTaskHistory: 'Error getting task history',
	sagaTextErrorUpdatingHistory: 'Error updating history list',

	sagaTextErrorCreatingTask: 'Task was not created',
	sagaTextErrorUpdatingTask: 'Task was not updated',
	sagaTextErrorDeletingTask: 'Task was not deleted',
	sagaTextErrorStartingTask: 'Task was not started',
	sagaToggleNotification: 'Task is now {{status, lowercase}}',

	sagaFailed: 'Scheduling Plugin: Unknown Error',

	sagaTextErrorInvalidLocation: 'Invalid Location',
	sagaTextErrorInvalidLocation_30013: 'Write permission is denied',
	sagaTextErrorInvalidLocation_30014: 'Delete permission is denied',
	sagaTextErrorInvalidLocation_30015: 'Location does not exist, or Read permission is denied',
	sagaTextErrorInvalidLocation_30016: 'Each schedule should correspond to a separate directory',
	sagaTextErrorInvalidLocation_30017: 'Read permission is denied',
	sagaTextSuccessVerifyLocation: 'Location verified',
	sagaTextSuccessMessageVerifyLocation: 'The Location inputed is valid',

	// Tabs
	'scheduleTasks!name': 'Tasks',
	'scheduleTasks!description': 'Scheduled tasks for the document',

	'scheduleHistory!name': 'History',
	'scheduleHistory!description': 'Scheduled task execution history',

	// Timezone
	taskExecutingTimezone: 'Executing Timezone',
	'timezone_Etc/GMT+11': '(UTC-11:00) Coordinated Universal Time-11',
	'timezone_America/Adak': '(UTC-10:00) Aleutian Islands',
	'timezone_Pacific/Honolulu': '(UTC-10:00) Hawaii',
	'timezone_Pacific/Marquesas': '(UTC-09:30) Marquesas Islands',
	'timezone_America/Anchorage': '(UTC-09:00) Alaska',
	'timezone_Etc/GMT+9': '(UTC-09:00) Coordinated Universal Time-09',
	'timezone_America/Tijuana': '(UTC-08:00) Baja California',
	'timezone_Etc/GMT+8': '(UTC-08:00) Coordinated Universal Time-08',
	'timezone_America/Los_Angeles': '(UTC-08:00) Pacific Time (US & Canada)',
	'timezone_America/Phoenix': '(UTC-07:00) Arizona',
	'timezone_America/Chihuahua': '(UTC-07:00) Chihuahua, La Paz, Mazatlan',
	'timezone_America/Denver': '(UTC-07:00) Mountain Time (US & Canada)',
	'timezone_America/Guatemala': '(UTC-06:00) Central America',
	'timezone_America/Chicago': '(UTC-06:00) Central Time (US & Canada)',
	'timezone_Pacific/Easter': '(UTC-06:00) Easter Island',
	'timezone_America/Mexico_City': '(UTC-06:00) Guadalajara, Mexico City, Monterrey',
	'timezone_America/Regina': '(UTC-06:00) Saskatchewan',
	'timezone_America/Bogota': '(UTC-05:00) Bogota, Lima, Quito, Rio Branco',
	'timezone_America/Cancun': '(UTC-05:00) Chetumal',
	'timezone_America/New_York': '(UTC-05:00) Eastern Time (US & Canada)',
	'timezone_America/Port-au-Prince': '(UTC-05:00) Haiti',
	'timezone_America/Havana': '(UTC-05:00) Havana',
	'timezone_America/Indiana/Indianapolis': '(UTC-05:00) Indiana (East)',
	'timezone_America/Grand_Turk': '(UTC-05:00) Turks and Caicos',
	'timezone_America/Asuncion': '(UTC-04:00) Asuncion',
	'timezone_America/Halifax': '(UTC-04:00) Atlantic Time (Canada)',
	'timezone_America/Caracas': '(UTC-04:00) Caracas',
	'timezone_America/Cuiaba': '(UTC-04:00) Cuiaba',
	'timezone_America/La_Paz': '(UTC-04:00) Georgetown, La Paz, Manaus, San Juan',
	'timezone_America/Santiago': '(UTC-04:00) Santiago',
	'timezone_America/St_Johns': '(UTC-03:30) Newfoundland',
	'timezone_America/Araguaina': '(UTC-03:00) Araguaina',
	'timezone_America/Sao_Paulo': '(UTC-03:00) Brasilia',
	'timezone_America/Cayenne': '(UTC-03:00) Cayenne, Fortaleza',
	'timezone_America/Argentina/Buenos_Aires': '(UTC-03:00) City of Buenos Aires',
	'timezone_America/Godthab': '(UTC-03:00) Greenland',
	'timezone_America/Montevideo': '(UTC-03:00) Montevideo',
	'timezone_America/Punta_Arenas': '(UTC-03:00) Punta Arenas',
	'timezone_America/Miquelon': '(UTC-03:00) Saint Pierre and Miquelon',
	'timezone_America/Bahia': '(UTC-03:00) Salvador',
	'timezone_Etc/GMT+2': '(UTC-02:00) Coordinated Universal Time-02',
	'timezone_Atlantic/Azores': '(UTC-01:00) Azores',
	'timezone_Atlantic/Cape_Verde': '(UTC-01:00) Cabo Verde Is.',
	'timezone_Etc/UTC': '(UTC) Coordinated Universal Time',
	'timezone_Europe/London': '(UTC+00:00) Dublin, Edinburgh, Lisbon, London',
	'timezone_Atlantic/Reykjavik': '(UTC+00:00) Monrovia, Reykjavik',
	'timezone_Africa/Sao_Tome': '(UTC+00:00) Sao Tome',
	'timezone_Africa/Casablanca': '(UTC+01:00) Casablanca',
	'timezone_Europe/Berlin': '(UTC+01:00) Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna',
	'timezone_Europe/Budapest': '(UTC+01:00) Belgrade, Bratislava, Budapest, Ljubljana, Prague',
	'timezone_Europe/Paris': '(UTC+01:00) Brussels, Copenhagen, Madrid, Paris',
	'timezone_Europe/Warsaw': '(UTC+01:00) Sarajevo, Skopje, Warsaw, Zagreb',
	'timezone_Africa/Lagos': '(UTC+01:00) West Central Africa',
	'timezone_Asia/Amman': '(UTC+02:00) Amman',
	'timezone_Europe/Bucharest': '(UTC+02:00) Athens, Bucharest',
	'timezone_Asia/Beirut': '(UTC+02:00) Beirut',
	'timezone_Africa/Cairo': '(UTC+02:00) Cairo',
	'timezone_Europe/Chisinau': '(UTC+02:00) Chisinau',
	'timezone_Asia/Damascus': '(UTC+02:00) Damascus',
	'timezone_Asia/Hebron': '(UTC+02:00) Gaza, Hebron',
	'timezone_Africa/Johannesburg': '(UTC+02:00) Harare, Pretoria',
	'timezone_Europe/Kiev': '(UTC+02:00) Helsinki, Kyiv, Riga, Sofia, Tallinn, Vilnius',
	'timezone_Asia/Jerusalem': '(UTC+02:00) Jerusalem',
	'timezone_Europe/Kaliningrad': '(UTC+02:00) Kaliningrad',
	'timezone_Africa/Khartoum': '(UTC+02:00) Khartoum',
	'timezone_Africa/Tripoli': '(UTC+02:00) Tripoli',
	'timezone_Africa/Windhoek': '(UTC+02:00) Windhoek',
	'timezone_Asia/Baghdad': '(UTC+03:00) Baghdad',
	'timezone_Europe/Istanbul': '(UTC+03:00) Istanbul',
	'timezone_Asia/Riyadh': '(UTC+03:00) Kuwait, Riyadh',
	'timezone_Europe/Minsk': '(UTC+03:00) Minsk',
	'timezone_Europe/Moscow': '(UTC+03:00) Moscow, St. Petersburg',
	'timezone_Africa/Nairobi': '(UTC+03:00) Nairobi',
	'timezone_Asia/Tehran': '(UTC+03:30) Tehran',
	'timezone_Asia/Dubai': '(UTC+04:00) Abu Dhabi, Muscat',
	'timezone_Europe/Astrakhan': '(UTC+04:00) Astrakhan, Ulyanovsk',
	'timezone_Asia/Baku': '(UTC+04:00) Baku',
	'timezone_Europe/Samara': '(UTC+04:00) Izhevsk, Samara',
	'timezone_Indian/Mauritius': '(UTC+04:00) Port Louis',
	'timezone_Europe/Saratov': '(UTC+04:00) Saratov',
	'timezone_Asia/Tbilisi': '(UTC+04:00) Tbilisi',
	'timezone_Europe/Volgograd': '(UTC+04:00) Volgograd',
	'timezone_Asia/Yerevan': '(UTC+04:00) Yerevan',
	'timezone_Asia/Kabul': '(UTC+04:30) Kabul',
	'timezone_Asia/Tashkent': '(UTC+05:00) Ashgabat, Tashkent',
	'timezone_Asia/Yekaterinburg': '(UTC+05:00) Ekaterinburg',
	'timezone_Asia/Karachi': '(UTC+05:00) Islamabad, Karachi',
	'timezone_Asia/Qyzylorda': '(UTC+05:00) Qyzylorda',
	'timezone_Asia/Kolkata': '(UTC+05:30) Chennai, Kolkata, Mumbai, New Delhi',
	'timezone_Asia/Colombo': '(UTC+05:30) Sri Jayawardenepura',
	'timezone_Asia/Kathmandu': '(UTC+05:45) Kathmandu',
	'timezone_Asia/Almaty': '(UTC+06:00) Astana',
	'timezone_Asia/Dhaka': '(UTC+06:00) Dhaka',
	'timezone_Asia/Omsk': '(UTC+06:00) Omsk',
	'timezone_Asia/Yangon': '(UTC+06:30) Yangon (Rangoon)',
	'timezone_Asia/Bangkok': '(UTC+07:00) Bangkok, Hanoi, Jakarta',
	'timezone_Asia/Barnaul': '(UTC+07:00) Barnaul, Gorno-Altaysk',
	'timezone_Asia/Hovd': '(UTC+07:00) Hovd',
	'timezone_Asia/Krasnoyarsk': '(UTC+07:00) Krasnoyarsk',
	'timezone_Asia/Novosibirsk': '(UTC+07:00) Novosibirsk',
	'timezone_Asia/Tomsk': '(UTC+07:00) Tomsk',
	'timezone_Asia/Shanghai': '(UTC+08:00) Beijing, Chongqing, Hong Kong, Urumqi',
	'timezone_Asia/Irkutsk': '(UTC+08:00) Irkutsk',
	'timezone_Asia/Singapore': '(UTC+08:00) Kuala Lumpur, Singapore',
	'timezone_Australia/Perth': '(UTC+08:00) Perth',
	'timezone_Asia/Taipei': '(UTC+08:00) Taipei',
	'timezone_Asia/Ulaanbaatar': '(UTC+08:00) Ulaanbaatar',
	'timezone_Australia/Eucla': '(UTC+08:45) Eucla',
	'timezone_Asia/Chita': '(UTC+09:00) Chita',
	'timezone_Asia/Tokyo': '(UTC+09:00) Osaka, Sapporo, Tokyo',
	'timezone_Asia/Pyongyang': '(UTC+09:00) Pyongyang',
	'timezone_Asia/Seoul': '(UTC+09:00) Seoul',
	'timezone_Asia/Yakutsk': '(UTC+09:00) Yakutsk',
	'timezone_Australia/Adelaide': '(UTC+09:30) Adelaide',
	'timezone_Australia/Darwin': '(UTC+09:30) Darwin',
	'timezone_Australia/Brisbane': '(UTC+10:00) Brisbane',
	'timezone_Australia/Sydney': '(UTC+10:00) Canberra, Melbourne, Sydney',
	'timezone_Pacific/Port_Moresby': '(UTC+10:00) Guam, Port Moresby',
	'timezone_Australia/Hobart': '(UTC+10:00) Hobart',
	'timezone_Asia/Vladivostok': '(UTC+10:00) Vladivostok',
	'timezone_Australia/Lord_Howe': '(UTC+10:30) Lord Howe Island',
	'timezone_Pacific/Bougainville': '(UTC+11:00) Bougainville Island',
	'timezone_Asia/Srednekolymsk': '(UTC+11:00) Chokurdakh',
	'timezone_Asia/Magadan': '(UTC+11:00) Magadan',
	'timezone_Pacific/Norfolk': '(UTC+11:00) Norfolk Island',
	'timezone_Asia/Sakhalin': '(UTC+11:00) Sakhalin',
	'timezone_Pacific/Guadalcanal': '(UTC+11:00) Solomon Is., New Caledonia',
	'timezone_Asia/Kamchatka': '(UTC+12:00) Anadyr, Petropavlovsk-Kamchatsky',
	'timezone_Pacific/Auckland': '(UTC+12:00) Auckland, Wellington',
	'timezone_Etc/GMT-12': '(UTC+12:00) Coordinated Universal Time+12',
	'timezone_Pacific/Fiji': '(UTC+12:00) Fiji',
	'timezone_Pacific/Chatham': '(UTC+12:45) Chatham Islands',
	'timezone_Etc/GMT-13': '(UTC+13:00) Coordinated Universal Time+13',
	'timezone_Pacific/Tongatapu': "(UTC+13:00) Nuku'alofa",
	'timezone_Pacific/Apia': '(UTC+13:00) Samoa',
	'timezone_Pacific/Kiritimati': '(UTC+14:00) Kiritimati Island',

	// Reporting Plugin Exceptions
	reportingPluginUnknown: 'An unknown error occurred during task execution',
	reportingPluginLrt: 'An LRT exception occurred in reporting plugin',
	reportingPluginBadResponse: 'Worker responded with error',
	reportingPluginStreaming: 'An error occurred during streaming from worker',
	reportingPluginResponseVerification: 'An error have been revealed after streaming result from worker',

	// Worker Exceptions
	reportingWorkerExportInvalidParameters: 'Invalid report parameters',
	reportingWorkerExportUnknownRenderingExt: 'Unknown rendering extension {0}',

	reportingWorkerTaskInitUnknown: 'An unknown error occurred during worker task execution: {0}',
	reportingWorkerTaskInitFileNotFound: 'File {0} not found',
	reportingWorkerTaskInitUnableToLoadFile: 'Unable to load file {0}',

	reportingWorkerFailCheckInvalidParameters: 'Invalid report parameters',
	reportingWorkerFailCheckUnknown: 'An unknown error occurred during worker task execution: {0}',
	reportingWorkerFailCheckNoDataset: 'Dataset not specified',

	reportingWorkerRenderingDatasetNotFound: 'Specified dataset not found or inaccessible due to insufficient permissions',
	reportingWorkerRenderingDatasourceNotFound: 'Specified datasource not found or inaccessible due to insufficient permissions',
	reportingWorkerRenderingUnknown: 'An unknown error occurred during worker task execution: {0}',

	reportingWorkerReportUnknown: 'An unknown error occurred when getting report info: {0}',
	reportingWorkerReportCyclicParameterReferences: 'Cyclic report parameter references detected',
	// TODO, please move to report plugin in future.
	'reporting_worker_fail_check_no_dataset': 'An error occurred during report fail check procedure: Dataset not specified',

	// Relative Dates
	dtTextBack: 'Back to Calendar',
	tbSpecificDate: 'Specific date',
	tbRelativeDate: 'Relative date',
	rdDay: 'day',
	rdWeek: 'week',
	rdMonth: 'month',
	rdQuarter: 'quarter',
	rdYear: 'year',
	rdCurrent: 'current',
	rdPrevious: 'previous',
	rdNext: 'next',
	rdBeginning: 'beginnig',
	rdEnd: 'end'
};
