export const tenantEN: LanguageKeyValueMap = {
	Yes: 'Yes',
	Close: 'Close',
	tntTenantSchema: 'Organization Schema',
	tntAddTenant: 'Add Organization',
	tntEditTenant: 'Edit Organization',
	tntNoItemsTip: 'no items',
	tntAddProp: 'Add Property',
	tntAddTenantProp: 'Add Organization Property',
	tntEditTenantProp: 'Edit Organization Property',
	tntPropName: 'Property Name',
	tntPropVlue: 'Property Value',
	tntRequired: 'Required',
	tntMultivalued: 'Multivalued',
	tntClose: 'Close',
	tntDelete: 'Delete Forever',
	tntEdit: 'Edit',
	tntName: 'Name',
	tntFromEmail: 'From Email',
	tntMultiLineTip: 'One value per line',
	tntAdd: 'Add',
	tntSave: 'Save',
	tntCancel: 'Cancel',
	tntTenantMembers: 'Organization Members',
	tntSelectMembers: 'Select Members',
	tntUsername: 'Username',
	tntEmail: 'Email',
	tntProvider: 'Provider',
	tntMembers: '{{count}} member(s)',
	tntDeleteTenantProp: 'Delete Organization Property',
	tntDeleteTenantPropConfirmMessage: 'Do you want to delete organization property "{{tenantPropName}}" permanently?',
	tntDeleteTenant: 'Delete Organization',
	tntDeleteTenantConfirmMessage: 'Do you want to delete organization "{{tenantName}}" permanently?',
	tntNoMemberTip: 'No Users in the organization. Please click ',
	tntAddMember: 'Add',

	tntTenantBasicInformation: 'Basic Information',
	tntTenantRoles: 'Organization Roles',
	tntSelectRoles: 'Select Roles',
	tntTenantMoveUp: 'Move Up',
	tntTenantMoveDown: 'Move Down',
	tntExpandAll: 'Expand All',
	tntCollapseAll: 'Collapse All',
	tntActions: 'Actions',
	tntGlobal: 'Global',
	tntRoleName: 'Role Name',
	tntUsersNumber: 'Users Number',
	tntNewOrganization: 'NewOrganization',
	tntTenantPermissions: 'Permissions',
	tntNoRolesTip: 'No Roles in the organization.',
	tntNoPermissionsTip: 'No Permissions in the organization.',
	tntPermissionsName: 'Name',
	tntPermissionsDescription: 'Description',
	tntInvisible: 'Invisible',
	tntDisableSubView: 'Disable sub-organization view value',
	tntDisableSubEdit: 'Disable Sub-organization edit value',

	tntErrorOrganizationNameNull: 'Organization name is required.',
	tntErrorOrganizationNameDuplicated: 'Organization name is duplicated.',
	tntErrorInvalidCharInName: 'Organization name could not contain characters: < > / \\ $',
	tntErrorFromPropNull: 'Property value is required.',

	tntErrorOrganizationPropNameNull: 'Organization property name is required.',
	tntErrorOrganizationPropNameDuplicated: 'Organization property name is duplicated.',

	error_5001: 'Organization name can not be empty.',
	error_5002: 'Organization with name "{{TenantName}}" already exists.',
	error_5003: 'Organization property name can not be empty.',
	error_5004: 'Organization property with name "{{TenantPropName}}" already exists.',
	error_5005: 'The tenant property name "{{TenantPropName}}" is reserved.',
	error_5006: 'The from email "{{FromEmail}}" already exists.',
};

export const portalEN: LanguageKeyValueMap = {
	'account-management-organization!title': 'Organizations',
	'account-management-organization!description': 'Organization Management',
};
