export const roleES: LanguageKeyValueMap = {
	cmAdd: 'Add',
	cmSave: 'Save',
	cmCancel: 'Cancel',
	cmDelete: 'Delete',
	cmEmptyResult: 'empty result',
	cmMessageBox: 'Message',
	cmOK: 'OK',

	otExpandAll: 'Expand All',
	otCollapseAll: 'Collapse All',
	otOrganizationRoot: 'Global',
	cmAddRole: 'Add Role',
	rcDeleteRole: 'Delete Role',
	rcDeleteRoleConfirmMessage: 'Are you sure you want to delete the role "{{RoleName}}"?',
	rcRoleName: 'Role Name',
	ecRoleMembers: 'Role Members',
	ecPermissions: 'Permissions',
	ecRoleColumn: 'Document List Columns',
	ecSelectMembers: 'Select Members',
	ecUsername: 'Username',
	ecEmail: 'Email',
	ecProvider: 'Provider',
	ecMembers: '({{count}} members)',
	ecDeleteUser: 'Delete User',
	ecDeleteUserConfirmMessage: 'Are you sure you want to remove the user "{{UserName}}" from the role?',
	ecNoMemberTip: 'No users under the role, to add, please click',

	dlType: 'Type',
	dlUpdateBy: 'Updated By',
	dlUpdated: 'Updated',
	ColumnName: 'Column Name',
	ShowInList: 'Show In List',
	documentListColumnsHint: 'Column settings only affect the document portal.',
	updateRoleDocumentColumnsError: 'Update failed',

	rmError_003: 'You don\'t have sufficient privileges to do the operation.',
	rmError_2001: 'Role "{{name}}" already exists.',
	rmError_2004: 'Can not update the members of role "everyone".',
	rmError_2005: 'Can not remove the member "admin" from role "administrator". ',
	rmError_2006: 'Can not update the permissions of role "administrator".',
	rmError_2010: 'Can not create a built-in role named "{{name}}"',
	rmError_5010: 'You cannot remove yourself from the current organization.',
	rmError_5011: 'You cannot remove yourself from the current organization role.',
};