export const portalES: LanguageKeyValueMap = {
	failed: 'Failed',
	'systemDiagnostic!title': 'System Diagnostic',
	'systemDiagnostic!description': 'System Diagnostic',
	monitoring: 'Monitoring',
	diagnosticLogsDownload: 'Diagnostic Logs Download',
	all: 'All',
	nodeName: 'Node Name',
	serviceName: 'Service Name',
	timeRange: 'Time Range',
	Min_1: '1 Minute',
	Min_15: '15 Minutes',
	Min_30: '30 Minutes',
	utilization: '{{percent}} Utilization',
	second: '{{time}} Seconds',
	minute: '{{time}} Minutes',
	secondTimeUnit: '60 (seconds)',
	minute15TimeUnit: '15 (minutes)',
	minute30TimeUnit: '30 (minutes)',
	cpuUsage: 'CPU Usage(%)',
	memUsage: 'Memory Usage(M)',
	today: 'Today',
	memEmpty: 'No memory  diagnostic information has been collected yet.',
	cpuEmpty: 'No cpu diagnostic information has been collected yet.',
	Logs: 'All Logs',
	SystemLog: 'System Log',
	ServerLog: 'Server Log',
	PortalLog: 'Portal Log',
	WorkerLog: 'Report Worker Log',
	CotWorkerLog: 'CotWorker Log',
	DashboardWorkerLog: 'Dashboard Worker Log',
	JavaDatasourceLog: 'Java DataSource Log',
	last1Day: 'Last 1 Day',
	last7Days: 'Last 7 Days',
	last30Days: 'Last 30 Days',
	customize: 'Customize',
	from: 'From',
	to: 'To',
	sysLogs: 'System Logs',
	'sysLogs!description': 'System Logs',
	sysInfo: 'System Information',
	'sysInfo!description': 'Download your system information: the type of the operation system and the system version',
	sysConf: 'Wyn Configuration',
	'sysConf!description': 'Download your desensitized wyn configuration file',
	downloadLog: 'Download',
	'shortcut-systemDiagnostic!props!text': 'System Diagnostic',
};
