export const rolePL: LanguageKeyValueMap = {
	cmAdd: 'Add',
	cmSave: 'Save',
	cmCancel: 'Cancel',
	cmDelete: 'Delete',
	cmEmptyResult: 'empty result',
	cmMessageBox: 'Wiadomość', // Message
	cmOK: 'OK',

	otExpandAll: 'Expand All',
	otCollapseAll: 'Collapse All',
	otOrganizationRoot: 'Global',
	cmAddRole: 'Add Role',
	rcDeleteRole: 'Delete Role',
	rcDeleteRoleConfirmMessage: 'Are you sure you want to delete the role "{{RoleName}}"?',
	rcRoleName: 'Role Name',
	ecRoleMembers: 'Role Members',
	ecPermissions: 'Permissions',
	ecSelectMembers: 'Select Members',
	ecUsername: 'Username',
	ecEmail: 'Email',
	ecProvider: 'Provider',
	ecMembers: '({{count}} members)',
	ecDeleteUser: 'Delete User',
	ecDeleteUserConfirmMessage: 'Are you sure you want to remove the user "{{UserName}}" from the role?',
	ecNoMemberTip: 'No users under the role, to add, please click',

	rmError_2001: 'Role "{{name}}" already exists.',
	rmError_2004: 'Can not update the members of role "everyone".',
	rmError_2005: 'Can not remove the member "admin" from role "administrator". ',
	rmError_2006: 'Can not update the permissions of role "administrator".',
	rmError_2010: 'Can not create a built-in role named "{{name}}"',
	rmError_5010: 'You cannot remove yourself from the current organization.',
};